### ISSUE TITLE
SQL - Syntax error when there is a dash in the URL

### ISSUE THREAD

**Issue by lato333** [commixproject/commix#104]
When there is a dash in the URL, I get an SQL-Syntax error:
```
#commix --url http://www.sample-url.com
...
Critical: Near "-": syntax error. You are advised to rerun with switch '--flush-session'.
```

**Fix that worked for me:**
Replace
https://github.com/commixproject/commix/blob/ca0227d5fc862a1d453cb0df85feef61283516c2/src/utils/session_handler.py#L38
with:
`table_name =  "session_" + host.replace(".","_").replace(":","_").replace("-","_") `

**Comment by stasinopoulos** [comment]
Thanks, i'll check it out :)
