### ISSUE TITLE
"Provided parameters are not in the appropriate format"

### ISSUE THREAD

**Issue by braimee** [commixproject/commix#106]
Hi there,

Hoping I can get a little guidance into narrowing down the cause of a `Provided parameters are not in the appropriate format` error.

Background: my client has a Web site with a contact form that we've identified as being vulnerable to command injection.  It's a simple form with:

* Name
* Subject
* Message

The POST body has something like:

````
_blahblah=123&_blah_version=456&name=MYNAME&email=THIS-IS-VULNERABLE&subject=BLAH
````

I'd like to leverage commix to test this further.  I'm using `-u` for the URL of the post form and `--data` with the long `_blahblah.....subject=BLAH` string and `-p email`.  I'm proxying through Burp and everything looks right, but I always get the "Provided parameters are not in the appropriate format."  I've tried leaving `-p` out too.

Is there anything you'd recommend I do to narrow down what exactly is causing this?

Thanks,
Brian

**Comment by stasinopoulos** [comment]
Hey @braimee, could you please provide me more information about this issue?
  The version of commix.
  The command(s) you have entered (i.e screenshot).

**Comment by braimee** [comment]
Hey there, thanks for the reply.  I ended up checking the possible command injection with a few other tools and it ended up being a false positive, but next time I've got problem with "a live one" I'll ping the issues list here.  Thanks again!
