### ISSUE TITLE
Code not running

### ISSUE THREAD

**Issue by bob989** [commixproject/commix#107]
When i run the code there is an error at line 84. The error is:
File "commix.py", line 84
    print settings.print_critical_msg(err_msg)
                 ^
SyntaxError: invalid syntax
![error](https://user-images.githubusercontent.com/33074141/31970565-278e5a5c-b964-11e7-8361-853e2503e8fd.JPG)

**Comment by stasinopoulos** [comment]
Hello @bob989, use Python version 2.6.x or 2.7.x.
