### ISSUE TITLE
reverse_tcp fails after 'FAILED_TRIES' update

### ISSUE THREAD

**Issue by vmotos** [commixproject/commix#109]
After updating commix today, I've received the following error when I try a reverse_tcp connection:

    if tries < (settings.FAILED_TRIES / 2):
AttributeError: 'module' object has no attribute 'FAILED_TRIES'

**Comment by stasinopoulos** [comment]
Fixed https://github.com/commixproject/commix/commit/63d92f2c3c4a07f381a324732c8e667e9f0947a1. Please update and check again.
