### ISSUE TITLE
commix.py: error: no such option: --base64

### ISSUE THREAD

**Issue by fede333lago** [commixproject/commix#155]
Hi, I'm having an issue using the base64 encoding in commix. I've cloned the latest version from the repo on Debian buster/sid. 

When I try to run the command like this:

./commix.py --url 'http://10.10.10.79/encode/decode.php' --data 'text=test' --base64 -p text

I get  commix.py: error: no such option: --base64
Commix version shows v2.3-dev#39

Is this encoding deprecated? Thanks!

**Comment by stasinopoulos** [comment]
Hello @fede333lago, you can use `--tamper="base64encode"` option.
