### ISSUE TITLE
Feature Request: Timeout Function

### ISSUE THREAD

**Issue by xsuperbug** [commixproject/commix#156]
"timeout" function can use for time-based attacks. This command works on both Linux and Windows. I also think there are many different uses.

for example, Linux:
timeout 3 ping -n 127.0.0.1 --> Waiting for 3 sec

Windows : 
Timeout 3 --> Waiting for 3 sec
Time^out 3 --> Waiting for 3 sec

**Comment by stasinopoulos** [comment]
Added a new tamper script "sleep2timeout.py" that uses "timeout" function for time-based attacks. https://github.com/commixproject/commix/commit/94d0ed64941cc55f7445fa7afb2f8895457956cf
