### ISSUE TITLE
Getting : Critical: The provided parameters are not in appropriate format.

### ISSUE THREAD

**Issue by santokri** [commixproject/commix#310]
I have attached the text file showing the critical error : santosh.txt
I have attached the RequestFile Im using XXX.txt
[santosh.txt](https://github.com/commixproject/commix/files/2140420/santosh.txt)
[XXX.txt](https://github.com/commixproject/commix/files/2140421/XXX.txt)

Please help to resolve this issue

**Comment by stasinopoulos** [comment]
Hello, try to remove the first "&" from the provided POST data and try again.
