### ISSUE TITLE
Feature request: New option to skip all upcoming similiar proceed questions

### ISSUE THREAD

**Issue by krisha** [commixproject/commix#359]
Thx for the nice tool!

It would be nice if you could add an option for Auto-Skip till next task on the question "How do you want to proceed?"

Commix repeats to ask me about how to proceed with unexpected time delays. Think if you get this message once it will repeat several times and always pause the process until interactions.

**Comment by stasinopoulos** [comment]
What about `--batch` option, that never asks for user input?
