### ISSUE TITLE
[x] Critical: Invalid header value ' \necho RQMFQERQMFQERQMFQE< nul'.

### ISSUE THREAD

**Issue by Himself132** [commixproject/commix#369]
## What's the problem (or question)?

Error is [x] Critical: Invalid header value ' \necho RQMFQERQMFQERQMFQE< nul'.

Verbose Logging shows - this is 15 minutes into it:

[*] Generating a payload for injection...
    |_ %20
echo%20RQMFQERQMFQERQMFQE<%20nul
[*] The provided HTTP request headers: 
    |_ POST /AuthenticationService.asmx
    |_ Content-Length: 331
    |_ Host: SCRUBBED
    |_ User-Agent:  
echo RQMFQERQMFQERQMFQE< nul
    |_ Connection: close
    |_ Referer: SCRUBBED
    |_ Content-Type: application/soap+xml; charset=utf-8
    |_ <?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
  <soap12:Body>
    <GetVersion xmlns="https://SCRUBBED/">1.1</GetVersion>
  </soap12:Body>
</soap12:Envelope>
[x] Critical: Invalid header value ' \necho RQMFQERQMFQERQMFQE< nul'.

## How can we reproduce the issue?

1. Here is the request and command

Untampered with request with custom injection marker
POST /AuthenticationService.asmx HTTP/1.1
Host: SCRUBBED
Content-Type: application/soap+xml; charset=utf-8
User-Agent: *
Content-Length: 322
Referer: SCRUBBED

<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
  <soap12:Body>
    <GetVersion xmlns="https://SCRUBBED/">1.1</GetVersion>
  </soap12:Body>
</soap12:Envelope>

Command
commix -r soap.txt --os=windows -H "Content-Type: application/soap+xml; charset=utf-8" --level=3 --force-ssl --os-cmd="shutdown /s" --ignore-redirects --skip-calc --flush-session -p "User-Agent" --all -v 4

The above command was run in many variations with the same results, tried some other options to see if i could get passed the error.

## What are the running context details?

* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`): apt-get

* Client OS (e.g. `Linux (Ubuntu)`) Linux Lumi 4.18.0-kali1-amd64 #1 SMP Debian 4.18.6-1kali1 (2018-09-10) x86_64 GNU/Linux

* Program version (`python commix.py --version` or `commix --version` depending on installation): v2.6-stable
* Target OS (e.g. `Linux (Debian)`): Windows 2012 R2
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`): NA
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works): NA, still detecting, no entry in user-agent string results in an error like:

<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><soap:Code><soap:Value>soap:Receiver</soap:Value></soap:Code><soap:Reason><soap:Text xml:lang="en">Server was unable to process request. ---&gt; Cannot insert the value NULL into column 'user_agent', table 'SCRUBBED.dbo.page_requests'; column does not allow nulls. INSERT fails.
The statement has been terminated.</soap:Text></soap:Reason><soap:Detail /></soap:Fault></soap:Body></soap:Envelope>

* Relevant console output (if any):  See above
* Exception traceback (if any): Se above

**Comment by Himself132** [comment]
I believe it _may_ have to do with the fact that the user-agent string is otherwise empty (excluding the * for the custom injection marker) and that the payload is %20 or a "space" which is probably where all white space would choke.  Just a hunch.

**Comment by stasinopoulos** [comment]
It seems similar to that issue https://github.com/commixproject/commix/issues/213
