### ISSUE TITLE
SSL/TLS Proxying does not work or target HTTPs proxy does not work

### ISSUE THREAD

**Issue by Himself132** [commixproject/commix#370]
## What's the problem (or question)?

Using BurpSuite proxy set to 127.0.0.1 :8080 with commix and --force-ssl and -r for POST body or u and https://url/?param=value does not work.

 

Must be self-signed certificate issue?

If this doesn't already exist as a change or improvement I'd consider adding it as many many people proxy tools to observe and tweak.

## How can we reproduce the issue?

1.  Attempt to proxy traffic destined for HTTPS or use force-ssl and push through proxy
2. Observe timeouts
3. Verbose logging does not show anything
4.

## What are the running context details?

* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`): apt-get
* Client OS (e.g. `Linux (Ubuntu)`) Linux Lumi 4.18.0-kali1-amd64 #1 SMP Debian 4.18.6-1kali1 (2018-09-10) x86_64 GNU/Linux
* Program version (`python commix.py --version` or `commix --version` depending on installation): 2.6 stable
* Target OS (e.g. `Linux (Debian)`):  NA
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`): NA
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works): NA
* Relevant console output (if any): NA
* Exception traceback (if any): NA

**Comment by stasinopoulos** [comment]
Hey @Himself132, thanks for the heads-up!

**Comment by Himself132** [comment]
Did you figure out what the issue was with this?

**Comment by stasinopoulos** [comment]
I found the cause of that issue and i am planning to proceed with an update soon (probably within this week).

**Comment by Himself132** [comment]
This is still an issue, if you use -r and a request piece or through burp with --proxy=https://127.0.0.1:8081 and with or without force-ssl it still times out
