### ISSUE TITLE
Issues regarding parsing HTTP headers from a file (i.e. `-r` option).

### ISSUE THREAD

**Issue by hadiirani** [commixproject/commix#378]
#############
in burp suit proxy:
#############
POST /mutillidae/webservices/soap/ws-lookup-dns-record.php HTTP/1.1
Accept-Encoding: gzip, deflate
Content-Type: text/xml;charset=UTF-8
SOAPAction: "urn:commandinjwsdl#commandinj"
Content-Length: 475
Host: 192.168.10.60
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)
Connection: close

<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:commandinjwsdl">
   <soapenv:Header/>
   <soapenv:Body>
      <urn:lookupDNS soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
         <targetHost xsi:type="xsd:string">INJECT_HERE</targetHost>
      </urn:lookupDNS>
   </soapenv:Body>
</soapenv:Envelope>

#####################
write burp request to  data.txt
#####################
commix > python commix.py -r "C:\data.txt" -v 4 

##############problem#############
Http Parser remove {SOAPAction: "urn:commandinjwsdl#commandinj"}  then "Internal Server Error"

commix > python commix.py -r "C:\data.txt" -v 4 -H SOAPAction:"urn:commandinjwsdl#commandinj" ...
dont work and repeat urn{because has :}
thank a lot

**Comment by stasinopoulos** [comment]
Hello, what version of commix do you use?

**Comment by hadiirani** [comment]
Hi
Last update at now :-) and previous versions!!

**Comment by stasinopoulos** [comment]
Hello @hadiirani, the provided SOAP data, seems to be invalid.
