### ISSUE TITLE
Getting Error 403 with Commix Running Against UBNT EdgeRouter

### ISSUE THREAD

**Issue by greg5678** [commixproject/commix#379]
I've been trying to run Commix against the URL `https://192.168.1.1/api/edge/feature.json` with the string `{"data":{"scenario":".Port_Forwarding","action":"load"}}`. This URL requires authentication so I logged into the EdgeRouter while monitoring for the cookie. I entered what I believed was needed for Commix to authenicate with the EdgeRouter but that turned out to be false and it returned error 403.
`python commix.py --force-ssl --url="https://192.168.1.1/api/edge/feature.json" --data='{"data":{"scenario":".Port_Forwarding","action":"load"}}' --cookie="PHPSESSID=c1405d73a76242dcac20ec2a4c117d76; X-CSRF-TOKEN=9fbebb63d405dd77d8d9f648a440d3d4508d3ff5c6045d7a364beffbfeb0741f; ip_address_top_user_option=total_bytes; beaker.session.id=c1405d73a76242dcac20ec2a4c117d76" --host="192.168.1.1" --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:61.0) Gecko/20100101 Firefox/61.0" --referer="https://192.168.1.1/"`

**Comment by stasinopoulos** [comment]
This is not a problem of commix, probably this error occurred due to the "X-CSRF-TOKEN".

**Comment by greg5678** [comment]
Okay. In that case the report can be closed.
