### ISSUE TITLE
Feature Request: Support for HTTP PUT request method 

### ISSUE THREAD

**Issue by arbazkiraak** [commixproject/commix#391]
Hello,

Thanks for creating this lovely project. I don't see any option to define the `HTTP REQUEST METHOD` , only `--data` is avaiable to supply the data values.

I would like to issue request in `PUT`

**Comment by arbazkiraak** [comment]
Hi @simonuvarov ,

Any update?

**Comment by stasinopoulos** [comment]
Currently commix does not support HTTP PUT request method, but this is actually on my todo-list. Thank you for your suggestion.
