### ISSUE TITLE
HTTPS Proxying Still Doesn't Work

### ISSUE THREAD

**Issue by Himself132** [commixproject/commix#415]
## What's the problem (or question)?
 Timeouts
 Works with SSL proxying 

## Do you have an idea for a solution?
 N/A
 N/A

## How can we reproduce the issue?

1. Find a site with SSL
2. Use proxy with and without --force-ssl switch, and with -r or -u for request file or url
3. watch timeout occur
4. N/A

## What are the running context details?

* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`): apt-get 
* Client OS (e.g. `Linux (Ubuntu)`) Linux 4.18.0-kali3-amd64 #1 SMP Debian 4.18.20-2kali2 (2018-11-30) x86_64 GNU/Linux
* Program version (`python commix.py --version` or `commix --version` depending on installation): 2.7 stable
* Target OS (e.g. `Linux (Debian)`): N/A
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`):
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works): N/A
* Relevant console output (if any): [x] Critical: Unable to connect to the target URL or proxy (127.0.0.1:8081).

* Exception traceback (if any): N/A

**Comment by stasinopoulos** [comment]
Hello @Himself132.

I am not able to reproduce that issue:
![commix](https://user-images.githubusercontent.com/5289251/50993685-f2e9f100-1522-11e9-9ed0-0c5cabb993fe.png)

![burp](https://user-images.githubusercontent.com/5289251/50993702-faa99580-1522-11e9-8527-79f3c8981090.png)

**Comment by Himself132** [comment]
The problem was I was also trying to do –ignore-401 through BURP and modified response headers to 200 OK and the connection issue was thrown.

 

So it is working as designed.
