### ISSUE TITLE
Feature Request: Python 3 support

### ISSUE THREAD

**Issue by XVilka** [commixproject/commix#420]
Python 2 will be dead in a year, it makes sense to start porting now.

**Comment by nanoRoot1** [comment]
utilizo la ultima version de python 3,
obtengo este error : 
[x] Critical: Incompatible Python version (3.7.0) detected. Use Python version 2.6.x or 2.7.x.

Cuando sera el soporte con python 3

**Comment by stasinopoulos** [comment]
@nanoRoot1 in English please.

**Comment by q2dg** [comment]
He/She simply says Python3 doesn't work. 
Resolving this issue is a MUST
Thanks, anyway
