### ISSUE TITLE
Feature Request: System install (as a module) support and setup.py for easier installation

### ISSUE THREAD

**Issue by blshkv** [commixproject/commix#433]
Please have a look at https://github.com/laramies/theHarvester/issues/52 for reasons why it is important for us.
You can also have a look at the following example on the implementation:
https://github.com/laramies/theHarvester/pull/229

**Comment by stasinopoulos** [comment]
Hello @blshkv 

Kindly confirm that the attached [setup.py.zip](https://github.com/commixproject/commix/files/4396931/setup.py.zip) is ok :)

**Comment by blshkv** [comment]
Thanks for working on it. I have downloaded the latest git, dropped setup.py into the folder, the output was the following:
```
~/Downloads/commix-master $ python setup.py install --user
<skip>
creating dist
creating 'dist/commix-3.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing commix-3.0-py3.6.egg
creating /home/blshkv/.local/lib64/python3.6/site-packages/commix-3.0-py3.6.egg
Extracting commix-3.0-py3.6.egg to /home/blshkv/.local/lib64/python3.6/site-packages
  File "/home/blshkv/.local/lib64/python3.6/site-packages/commix-3.0-py3.6.egg/src/core/modules/shellshock/shellshock.py", line 428
    except _urllib.error.HTTPError, warn_msg:
                                  ^
SyntaxError: invalid syntax

Adding commix 3.0 to easy-install.pth file
Installing commix script to /home/blshkv/.local/bin
```

**Comment by stasinopoulos** [comment]
patch done @ https://github.com/commixproject/commix/commit/3a3188cc230f71e1b0015a720b80cee01fa3142f :)

**Comment by blshkv** [comment]
installed it the latest:
```
git clone https://github.com/commixproject/commix 
python3 setup.py install --user
```
and got this:
~/.local/bin/commix 
Traceback (most recent call last):
  File "/home/blshkv/.local/bin/commix", line 11, in <module>
    load_entry_point('commix==3.0', 'console_scripts', 'commix')()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'commix'

**Comment by stasinopoulos** [comment]
Please take a look at this: [setup.py.zip](https://github.com/commixproject/commix/files/4508686/setup.py.zip)

**Comment by blshkv** [comment]
Can you please test it before asking?
It fails with exact the same message. You might need to restructure directories too.
```
/data/virtualenv/pelican $ ./bin/commix 
Traceback (most recent call last):
  File "./bin/commix", line 11, in <module>
    load_entry_point('commix==3.1', 'console_scripts', 'commix')()
  File "/data/virtualenv/pelican/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/virtualenv/pelican/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/data/virtualenv/pelican/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/data/virtualenv/pelican/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'commix'
```

**Comment by stasinopoulos** [comment]
That [setup.py](https://github.com/commixproject/commix/files/4515166/setup.py.zip) works fine for me.

![Screenshot 2020-04-22 at 12 30 28 PM](https://user-images.githubusercontent.com/5289251/79965982-6ce28700-8495-11ea-8f4d-7cedd4f4a890.png)

**Comment by blshkv** [comment]
Ill test with python 3.7 in a bit. Have seen such problem with 3.6 recently

**Comment by stasinopoulos** [comment]
Cool! Please download and try the latest [setup.py](https://github.com/commixproject/commix/files/4515166/setup.py.zip)

**Comment by blshkv** [comment]
ok, it works with python 3.7

The root cause seems mutual imports:
https://stackoverflow.com/questions/1250103/attributeerror-module-object-has-no-attribute
Basically, Python3.7 can handle it, see https://docs.python.org/3/whatsnew/3.7.html#importlib-resources

Not sure if you want to fix the code or lift the requirement. I would suggest fixing the code.
Here is an example: https://github.com/laramies/theHarvester/pull/234

**Comment by stasinopoulos** [comment]
Added https://github.com/commixproject/commix/commit/df5544d2b8f5dcb10e1fb3ec9d4b3cc0ef682106

**Comment by blshkv** [comment]
great job, thanks. Would be good to have a fresh release too, since the previous version does not support python3 (if I'm not wrong).
