### ISSUE TITLE
What's mean  invalid continuation byte ?

### ISSUE THREAD

**Issue by maxiaoxian** [commixproject/commix#442]
[*] Testing the (results-based) classic command injection technique... [x] Critical: 'utf8' codec can't decode byte 0xc7 in position 2851: invalid continuation byte

**Comment by maxiaoxian** [comment]
./commix.py  --url="http://192.168.56.101/DVWA/vulnerabilities/exec/"  --data="ip=127.0.0.1&Submit=submit" --cookie="security=high; PHPSESSID=90kl3v5ao730t2osae9ldlj66l"  --skip-waf  --skip-calc

**Comment by stasinopoulos** [comment]
Hey @maxiaoxian, could you please provide me with more information about this bug such as the version of Commix, OS and the Python version.

**Comment by maxiaoxian** [comment]
This can be tested in dvwa version 1.0.7, but  will be thrown in dvwa version 1.9

**Comment by stasinopoulos** [comment]
Hello @maxiaoxian, what version of commix do you use?

**Comment by maxiaoxian** [comment]
@stasinopoulos  master branch

**Comment by stasinopoulos** [comment]
Hello @maxiaoxian, i am not able to reproduce the error.
I use the latest version of commix (dev) and DVWA version 1.10.
