### ISSUE TITLE
check_connection(url) 

### ISSUE THREAD

**Issue by dabing1205** [commixproject/commix#449]
## What's the problem (or question)?
run commix with below url
python commix.py --url="http://172.18.18.77:8081/vulnerabilities/exec/"

Exception:
[*] Resolving hostname '127.0.0.1:8081'.
[x] Critical: Host '127.0.0.1:8081' does not exist.

## Do you have an idea for a solution?
source: commix/src/core/injections/controller/checks.py
solution:
line 142:
from：   if not re.search(r"\A\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\Z", hostname):
to：        if not re.search(r"\A\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}", hostname):

Reason:
urlparse(url).netloc will get 127.0.0.1:8081, not match the re.search

**Comment by stasinopoulos** [comment]
Hello @dabing1205, what version of commix do you use? 
Also, could you please paste a screenshot of that issue?

**Comment by dabing1205** [comment]
<img width="952" alt="874cf1573d9442e6195b2be14" src="https://user-images.githubusercontent.com/1543302/58232665-b352d180-7d6c-11e9-908c-1721ed1034ce.png">

**Comment by dabing1205** [comment]
I notice that the error code happened in line 142 check_connection function.

**Comment by stasinopoulos** [comment]
Thanks, i 'll check this out soon :).

**Comment by stasinopoulos** [comment]
Fixed https://github.com/commixproject/commix/commit/65fad20a9a7d6744c2d42b3e63ecd2bbd7ac92ee
