### ISSUE TITLE
Add Custom Injection Marker *

### ISSUE THREAD

**Issue by Himself132** [commixproject/commix#452]
## What's the problem (or question)? Feature Request - Add user-controlled custom injection marker
 N/A

Add * as a custom injection marker or some other syntax {INJECTION}, [INJECTION], etc. so that a user can control the place of injection in complex situations similar to sqlmap

## Do you have an idea for a solution?
 No
 Use some sqlmap code

## How can we reproduce the issue?

1. N/A
2. N/A
3. N/A
4. N/A

## What are the running context details?

* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`): apt-get
* Client OS (e.g. `Linux (Ubuntu)`) Linux 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-2kali1 (2019-05-15) x86_64 GNU/Linux
* Program version (`python commix.py --version` or `commix --version` depending on installation):  v2.8-stable
* Target OS (e.g. `Linux (Debian)`):  N/A
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`): N/A
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works): N/A
* Relevant console output (if any): N/A
* Exception traceback (if any): N/A

**Comment by stasinopoulos** [comment]
The asterisk (*) can also be used to point to the arbitrary injection point inside GET, POST or HTTP headers.
