### ISSUE TITLE
JSON Parsing Issue

### ISSUE THREAD

**Issue by Himself132** [commixproject/commix#475]
## What's the problem (or question)?
 Error and Abort Scanning

## Do you have an idea for a solution?
 ignore empty parameter name and inject at value

No

## How can we reproduce the issue?

1. run commix with JSON POST body via -r flag
2. ensure there is a JSON variable with a value but no name
3. observe error
4. file form1commix.txt contents issue is likely the empty "" with value true

POST /login HTTP/1.1
Host: SCRUBBED
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: application/json, text/plain
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://SCRUBBED
Content-Type: application/json;charset=utf-8
Content-Length: 75
Connection: close

{"email":"fake@fake.com","password":"SCRUBBED","audit":{"":true}}

## What are the running context details?

* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`): apt-get
* Client OS (e.g. `Linux (Ubuntu)`)  Linux 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali1 (2019-07-22) x86_64 GNU/Linux
* Program version (`python commix.py --version` or `commix --version` depending on installation): v2.9-stable
* Target OS (e.g. `Linux (Debian)`): N/A
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`): N/A
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works): N/A
* Relevant console output (if any):[*] Parsing HTTP request using the 'form1commix.txt' file... [ SUCCEED ]
[*] Checking connection to the target URL... [ SUCCEED ]
[*] Ignoring the stored session from the session file... [ SUCCEED ]
[!] Warning: Heuristics have failed to identify target application.
[?] JSON data found in POST data. Do you want to process it? [Y/n] > Y
[x] Critical: Unhandled exception occurred in '2.9-stable'. It is recommended to retry your run with the latest (dev) version from official GitHub repository at 'https://github.com/commixproject/commix.git'. If the exception persists, please open a new issue at 'https://github.com/commixproject/commix/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you.
Commix version: 2.9-stable
Python version: 2.7.16+
Operating system: posix
Command line: commix.py -r form1commix.txt --proxy=http://127.0.0.1:8080
[?] Do you want to automatically create a new (anonymized) issue with the unhandled exception information at the official Github repository? [y/N] N

* Exception traceback (if any):
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 885, in <module>
    main(filename, url)
  File "main.py", line 588, in main
    controller.do_check(url, filename)
  File "controller.py", line 605, in do_check
    perform_checks(url,filename)
  File "controller.py", line 528, in perform_checks
    basic_level_checks()
  File "controller.py", line 496, in basic_level_checks
    post_request(url, http_request_method, filename, timesec)
  File "controller.py", line 428, in post_request
    found_parameter = parameters.do_POST_check(parameter)
  File "parameters.py", line 292, in do_POST_check
    checks.is_empty(multi_parameters, http_request_method)
  File "checks.py", line 1103, in is_empty
    if len(multi_params[empty]) == 0:
TypeError: object of type 'bool' has no len()

**Comment by stasinopoulos** [comment]
Hey @Himself132 please update to the latest dev version and try again.

**Comment by Himself132** [comment]
i am unable to locate where to download the latest dev version, i only see master branch

**Comment by stasinopoulos** [comment]
You can download commix by cloning the Git repository:
`
git clone https://github.com/commixproject/commix.git commix`

**Comment by Himself132** [comment]
That downloads 2.8 stable, you can see above I'm on 2.9-stable.  Isn't that the most recent version?

The problem can be reproduced by using the exact command and request file as above.

**Comment by stasinopoulos** [comment]
FYI that git command downloads **the latest dev version** master branch. 
BTW the problem that you described, can't be reproduced in the latest dev version.

**Comment by Himself132** [comment]
I wish you wouldn't have closed this.  I tried the latest dev version master branch which for some weird reason is lower than your 2.9 stable and it gave the message there are no parameters.

Here are the details

commix.py --version
v2.8-stable

python commix.py -r commix1.txt --force-ssl --os=UNIX

POST /dir1/dir2/dir3/resource HTTP/1.1
Host: SCRUBBED
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: application/json, text/plain
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: SCRUBBED
Content-Type: application/json;charset=utf-8
Content-Length: 132
Cookie: SCRUBBED
Connection: close

{"Param1":["P1value1","P1value2"],"filters":{"search":""},"all":false,"Param2":true,"audit":{"Param3":"P3value1"}}
