### ISSUE TITLE
I wish you wouldn't have closed this.  I tried the latest dev version master branch which for some weird reason is lower than your 2.9 stable and it gave the message there are no parameters.

### ISSUE THREAD

**Issue by Himself132** [commixproject/commix#477]
I wish you wouldn't have closed this.  I tried the latest dev version master branch which for some weird reason is lower than your 2.9 stable and it gave the message there are no parameters.

Here are the details

commix.py --version
v2.8-stable

python commix.py -r commix1.txt --force-ssl --os=UNIX

POST /dir1/dir2/dir3/resource HTTP/1.1
Host: SCRUBBED
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: application/json, text/plain
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: SCRUBBED
Content-Type: application/json;charset=utf-8
Content-Length: 132
Cookie: SCRUBBED
Connection: close

{"Param1":["P1value1","P1value2"],"filters":{"search":""},"all":false,"Param2":true,"audit":{"Param3":"P3value1"}}

_Originally posted by @Himself132 in https://github.com/commixproject/commix/issues/475#issuecomment-519210660_

**Comment by Himself132** [comment]
[*] Parsing HTTP request using the 'commix1.txt' file... [ SUCCEED ]
[!] Warning: Current version seems to be out-of-date.
[?] Do you want to update to the latest version now? [Y/n] > n
[*] Resolving hostname 'stable.trustfile.avalara.com'.
[!] Warning: Got a 302 redirection (https://SCRUBBED).
[!] Warning: Got a 302 redirection (https://SCRUBBED.
[?] Do you want to follow the identified redirection? [Y/n] > n
[*] Checking connection to the target URL... [ SUCCEED ]
[!] Warning: Heuristics have failed to identify target application.
[?] JSON data found in POST data. Do you want to process it? [Y/n] > Y
[x] Critical: No parameter(s) found for testing in the provided data.

**Comment by stasinopoulos** [comment]
Update to the latest dev version.

**Comment by Himself132** [comment]
I did update to the latest dev version and i ran the command above. Using your git command copy and paste.  Did you update the dev version again or are you just closing the issue because you think i didn't use the latest dev version
