### ISSUE TITLE
Critical: Missing a mandatory option 

### ISSUE THREAD

**Issue by baobaovt** [commixproject/commix#487]
please help me for this problem . I ran commix.py on windows and this notification popup
so I have no idea to fix this . thanks for reading !

> [x] Critical: Missing a mandatory option (-u, -l, -m, -r, -x, --wizard, --update, --list-tampers, --purge or --dependencies). Use -h for help.

**Comment by stasinopoulos** [comment]
Hello, @baobaovt please take a look at the '**[usage examples](https://github.com/commixproject/commix/wiki/Usage-Examples)**' wiki page, where there are several test cases and attack scenarios.
