### ISSUE TITLE
Critical: You specified more than one testable parameters. Use the '-p' option to define them (i.e -p "id1,id2").

### ISSUE THREAD

**Issue by Parshuram2** [commixproject/commix#499]
## What's the problem (or question)?
When reading from a file, it always gives the above error. Even when only one param with -p is provided the same error comes again and again.

## How can we reproduce the issue?

1. Any form request on any website when captured through burpsuite has multiple params.
2. When a single parameter is specified with -p it doesn't work. Neither does -p "user,password"
3.
4.

## What are the running context details?

* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`): pre-installed
* Client OS (e.g. `Linux (Ubuntu)`) Linux Kali
* Program version (`python commix.py --version` or `commix --version` depending on installation): 2.9
* Target OS (e.g. `Linux (Debian)`):  Doesn't go that far
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`):doesn't go that far
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works): n/A
* Relevant console output (if any): Above message
* Exception traceback (if any):none

**Comment by matt115** [comment]
hello @Parshuram2; I got the same error. 
How do you have resolved the issue ?

**Comment by Parshuram2** [comment]
> hello @Parshuram2; I got the same error.
> How do you have resolved the issue ?

I didn't. I gave up on this and decided sqlmap is the best.
