### ISSUE TITLE
[x] Critical: 'utf-8' codec can't decode byte 0xec in position 488: invalid continuation byte

### ISSUE THREAD

**Issue by Tensha** [commixproject/commix#507]
Hello, new on this tool but used a lot of time sqlmap.

Im trying to make some test on sqlinjection vulnerable url like : http://xxxx.eu/dddd.asp?id=45 and i always get this error code(title error). What i can do?

In some other case i got " [x] Critical: 13."

Tryed so search around but i cant found nothing.
Thanks for helping

**Comment by stasinopoulos** [comment]
Hello @Tensha, firstly i would like to mention that commix **does not perform** SQL injection attacks. 
Nevertheless, I am not able to reproduce the error, could you please provide me with more information about this bug (such as the version of Commix, OS and the Python version).

**Comment by Tensha** [comment]
Kali linux latest version, 3.7.5 python.

Now i used (is POST search form)
sudo commix -u http://xxxx.eu/xxx.asp --data name=red

and he is testing. Really slow but he is testing.

But about the error, used a get request, i can share you the original url who give me cant decode etc.

`commix -u http://www.extremelot.eu/proc/arti/vediarte.asp?id=655


[*] Resolving hostname 'www.extremelot.eu'.
[*] Checking connection to the target URL... [ SUCCEED ]
[x] Critical: 'utf-8' codec can't decode byte 0xec in position 488: invalid continuation byte
`


Error 13 here:
`commix -u http://www.extremelot.eu/proc/schedapg/infopl.asp?ID=ACHILLE -v 4 --random-agent




[*] Resolving hostname 'www.extremelot.eu'.
[*] Fetching random HTTP User-Agent header... [ SUCCEED ]
[+] The fetched random HTTP User-Agent header is 'Mozilla/4.0 (compatible; MSIE 7.0b; Windows NT 6.0)'.
[*] Creating HTTP requests opener object.
[*] Checking connection to the target URL... 
[*] The target's request HTTP headers:
    |_ GET /proc/schedapg/infopl.asp?ID=ACHILLE HTTP/1.1
    |_ Accept-Encoding: identity
    |_ Host: www.extremelot.eu
    |_ User-Agent: Mozilla/4.0 (compatible; MSIE 7.0b; Windows NT 6.0)
    |_ Accept: */*
    |_ Connection: close
[*] The target's response HTTP headers (200):
    |_ Cache-Control: private
    |_ Content-Type: text/html
    |_ Server: Microsoft-IIS/8.5
    |_ Set-Cookie: ASPSESSIONIDQSATCBCS=IKLHGOBBNBEKKOHAIKCKMJHD; path=/
    |_ X-Powered-By: ASP.NET
    |_ X-Powered-By-Plesk: PleskWin
    |_ Date: Fri, 03 Jan 2020 13:32:22 GMT
    |_ Connection: close
    |_ Content-Length: 471
    |_ URI: http://www.extremelot.eu/proc/schedapg/infopl.asp?ID=ACHILLE
[*] The target's HTTP response page content:

<html>
<head><LINK REL=STYLESHEET TYPE='text/css' HREF='../../lotnew/styles/tables.css'><title></title>
</head>
<LINK REL=STYLESHEET TYPE="text/css" HREF='stile.css'>
<body bgcolor="#000000" topmargin="0" leftmargin="0">

	<table width="90%" align="center" border="0" cellspacing="0" cellpadding="3">
	
	
	<tr>
	   <td valign="top" class="titoli">Qualcosa su di me...</td>
	   <td class="testi_chiari">1</td>
	</tr>
	
	</table>
	<br>
	
</body>
</html>
[x] Critical: 13.
`

**Comment by Tensha** [comment]
I have another question for you:)
[ricercaposta.txt](https://github.com/commixproject/commix/files/4020241/ricercaposta.txt)

commix -r ricercaposta.txt

I give me back :
[x] Critical: You specified more than one injecton markers. Use the '-p' option to define them (i.e -p "id1,id2").

**Comment by stasinopoulos** [comment]
@Tensha open different issue for that.

**Comment by stasinopoulos** [comment]
Fixed https://github.com/commixproject/commix/commit/89693312c7b9d070ed31036fac1d1d03884d26d4
