### ISSUE TITLE
https scan issues

### ISSUE THREAD

**Issue by kaczalapa** [commixproject/commix#511]
While am trying to make scan while https connection the test is very slow with a lot of connection problems with returning requests. I was trying to put scan with a lot of ways (only URL [get parameteres], force-ssl, random agent). Any of these sollutions didnt work.
That problem doesnt exist in http connection. I think this is problem with https connection (it doesnt depend on type of certificate (fully trusted or self signed) - in both the problem is the same)

I dont have idea how to repair that. I think this is problem with https scan, but I dont know how can i better debug this issue.

Reproduce:
1. Run as root priviliges: commix -u https://website?par=value (blank/--force-ssl/--random-agent)

Logs from terminal:
[*] Resolving hostname 'website'.
[*] Fetching random HTTP User-Agent header... [ SUCCEED ]
[+] The fetched random HTTP User-Agent header is 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:9.0) Gecko/20100101 Firefox/9.0'.
[*] Checking connection to the target URL... [ FAILED ]
[x] Critical: Please wait while retring the request(s).
[!] Warning: In case the provided target URL is valid, try to rerun with the switch '--random-agent' and/or proxy switch.
[*] Please wait while retring the request(s).

* Installation method: both git clone (v3.1-dev#14) and apt-get (v3.0-stable);
* Client OS: Kali 2020.1
* Target OS: in private lab ubuntu bee-box 
* Command injection techniques found by commix: default method
* Results of manual target assessment: dont have result
* Relevant console output (if any): I gave above
* Exception traceback (if any): I gave above

Maybe it is problem in bad configuration of scan. I didnt have problem with scan http bee-box website, but if I tried to scan https bee-box site or some internal hosts everywhere I had a lot of warnings, critical informations and very slow output with response.

**Comment by stasinopoulos** [comment]
Hello @kaczalapa,
Sorry, but I am not able to reproduce the bug.

I used a request file:
> POST /bWAPP/commandi.php HTTP/1.1
> Host: x.x.x.x
> Connection: close
> Content-Length: 30
> Cache-Control: max-age=0
> Origin: https://x.x.x.x
> Upgrade-Insecure-Requests: 1
> Content-Type: application/x-www-form-urlencoded
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
> Sec-Fetch-Dest: document
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
> Sec-Fetch-Site: same-origin
> Sec-Fetch-Mode: navigate
> Sec-Fetch-User: ?1
> Referer: https://x.x.x.x/bWAPP/commandi.php
> Accept-Encoding: gzip, deflate
> Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
> Cookie: PHPSESSID=60ffab3b46f02f98add9d96bbc4521b1; security_level=0
> 
> target=www.nsa.gov&form=submit

And the following command:

> python commix.py -r req1.txt --force-ssl

<img width="1280" alt="Screenshot 2020-03-24 at 1 22 54 AM" src="https://user-images.githubusercontent.com/5289251/77372570-91502400-6d6e-11ea-8d79-b915cce06ab8.png">
