### ISSUE TITLE
Can't connect to any host under SSL

### ISSUE THREAD

**Issue by h0nus** [commixproject/commix#516]
## What's the problem (or question)?
Commix won' t connect to any target site under SSL, just hangs on "Checking connection to the target URL" message and even using -v 4 doesn't help.
On HTTP clear, it works normally.
The problem remains even on Python3.

## Do you have an idea for a solution?
I don't known.
I tried downgrading minimum cipher used on openssl.cnf, changing dns servers and even using a vpn without luck.

## How can we reproduce the issue?
commix --url "https://hostname/path/to/vuln.php?LG_HG=234&SC_WD=360" --technique=E --user-agent "Mozilla/5.0 (Linux; U; Android 4.0.3; en-us; LG-L160L Build/IML74K) AppleWebkit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"

## What are the running context details?
* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`): git clone
* Client OS (e.g. `Linux (Ubuntu)`): Ubuntu
* Program version (`python commix.py --version` or `commix --version` depending on installation): v3.1-dev#15
* Target OS (e.g. `Linux (Debian)`):  Linux
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`): Can't even connect
* Results of manual target assessment : Can't even connect. (btw the payload was simple `";print(md5(31337));$a="`)
* Relevant console output (if any): It just hangs at "Checking connection to the target URL"

![image](https://user-images.githubusercontent.com/23401728/75946469-84da5900-5e9d-11ea-984b-995b23a1ccd8.png)

* Exception traceback (if any): none

**Comment by stasinopoulos** [comment]
Similar https://github.com/commixproject/commix/issues/511

**Comment by stasinopoulos** [comment]
Hello @h0nus,
Please take a look at https://github.com/commixproject/commix/issues/511
Try to update to the latest (dev) version.

**Comment by maloba1** [comment]
some problem 
hangs on;
[*] Checking connection to the target URL...
