### ISSUE TITLE
critical error

### ISSUE THREAD

**Issue by yournainaidi** [commixproject/commix#521]
[*] Testing the (blind) time-based command injection technique... [ 0.5% ]
[x] Critical: URL can't contain control characters. 'default.jspa?id=\nstr=$(echo%20AQTDKI)\nstr1=$(expr%20length%20"$str")\nif%20[%201%20!=%20$str1%20]\nthen%20sleep%200\nelse%20sleep%201\nfi%20&returnUrl=/secure/issues' (found at least '\n').

**Comment by stasinopoulos** [comment]
Update to the latest dev version
