### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by yournainaidi** [commixproject/commix#522]
Accept: */*

login=Log%20In&atl_token=&os_cookie=true&os_destination=/default.jsp&os_password=g00dPa%24%24w0rD&os_username=reprdxux&user_role=

when the post data as up,

[!] Warning: The tested POST parameter 'login' seems to be not injectable.
[*] Setting the POST parameter 'os_cookie' for tests.
[*] Testing the (results-based) classic command injection technique... [x] Critical: You specified more than one injecton markers. Use the '-p' option to define them (i.e -p "id1,id2").

But I have not specified more than one injecton markers. Just using the default configure.

**Comment by stasinopoulos** [comment]
Update to the latest dev version
