### ISSUE TITLE
some interesting

### ISSUE THREAD

**Issue by yournainaidi** [commixproject/commix#524]
#coding:utf-8
import re
INJECT_TAG = "IIIIII"
PARAMETER_DELIMITER = "&"

def vuln_GET_param(url):
  urls_list = []
  # Define the vulnerable parameter
  if "?" not in url:
    #Grab the value of parameter.
    value = re.findall(r'/(.*)/' + INJECT_TAG + "", url)
    value = ''.join(value)
    vuln_parameter = re.sub(r"/(.*)/", "", value)

  elif re.findall(r"" + PARAMETER_DELIMITER + "(.*)=" + INJECT_TAG + "", url):
    vuln_parameter = re.findall(r"" + PARAMETER_DELIMITER + "(.*)=" + INJECT_TAG + "", url)
    vuln_parameter = ''.join(vuln_parameter)
    vuln_parameter = re.sub(r"(.*)=(.*)" + PARAMETER_DELIMITER, "", vuln_parameter)

  elif re.findall(r"\?(.*)=" + INJECT_TAG + "", url):
    vuln_parameter = re.findall(r"\?(.*)=" + INJECT_TAG + "", url)
    vuln_parameter = ''.join(vuln_parameter)

  elif re.findall(r"(.*)=" + INJECT_TAG + "", url):
    vuln_parameter = re.findall(r"(.*)=" + INJECT_TAG + "", url)
    vuln_parameter = ''.join(vuln_parameter)

  # Check if only one parameter supplied but, not defined the INJECT_TAG.
  elif INJECT_TAG not in url:
    #Grab the value of parameter.
    value = re.findall(r'\?(.*)=', url)
    value = ''.join(value)
    vuln_parameter = value

  else:
    vuln_parameter = url
  
  return vuln_parameter 

url = "https://github.com/commixproject/IIIIII"
print(vuln_GET_param(url))
url = "https://github.com/IIIIII/commix"
print(vuln_GET_param(url))
-------------------------------------------------------
the result as follows:
commixproject
/github.com

the function vuln_GET_param is from the newest version of commix.

**Comment by stasinopoulos** [comment]
what is that?
