### ISSUE TITLE
Run fails - Network is unreachable

### ISSUE THREAD

**Issue by juushya** [commixproject/commix#53]
Hi,

Just checked out the latest code on 2 (VM) boxes - Kali (via Kali repo) and Ubuntu (via git clone). Running commix fails when on a local, private network, i.e. without access to Internet. Not sure if this is by design.?

Easy to reproduce: change the network adaptor to Host-Only networking, and try running commix. It fails with:

```
# commix
[x] Critical: Network is unreachable.
```

**Comment by stasinopoulos** [comment]
Thanks for the heads up. :)
