### ISSUE TITLE
Unorthodox versioning

### ISSUE THREAD

**Issue by blshkv** [commixproject/commix#536]
## What's the problem (or question)?
This issue is similar with https://github.com/drwetter/testssl.sh/issues/1568
The current scheme has two incremental numbers
<X.Y>-<date>

Could you drop <date> please? It is informative and cool but not common and doesn't follow common software versioning:
https://en.wikipedia.org/wiki/Software_versioning

Unusual software versioning causes an additional work for Linux package maintainers like myself. For example, Gentoo portage system does not support - in the version number, and we have to spend extra time to come up with a fix instead of just coping a previous ebuild file.
Next, it might also cause similar problems with sites like https://repology.org/project/commix/versions where a software versioning is getting tracked and compared because each distro could name it differently. Some distributions just ignored the <date> suffix

## Do you have an idea for a solution?
Drop <date>

## How can we reproduce the issue?
yes

## What are the running context details?
no running

**Comment by stasinopoulos** [comment]
Hello @blshkv to the best of my knowledge -somehow- Kali Linux maintainers already solved that "issue".

**Comment by blshkv** [comment]
Yes, each distro have "solve" this issue as they think is right. That's why repology (see the link) can't detect what is the correct version. Please fix it here so it would be any discrepancy

**Comment by stasinopoulos** [comment]
Take a look at here: https://github.com/commixproject/commix/releases/tag/v3.1

**Comment by blshkv** [comment]
I did, and it is not consistent. I found a version it setup.py. it is called differently in each place. The tag is 3.1, the actual version is 3.1-dev (which is why we called it pre-release) and the tar ball is 3.1-<date>

**Comment by stasinopoulos** [comment]
Ok, i ll change this on my next stable release.

**Comment by stasinopoulos** [comment]
Done at v3.2.
