### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by liboLee** [commixproject/commix#537]
[critical] Unhandled exception occurred in '3.1-stable'. It is recommended to retry your run with the latest (dev) version from official GitHub repository at 'https://github.com/commixproject/commix.git'. If the exception persists, please open a new issue at 'https://github.com/commixproject/commix/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you.
Commix version: 3.1-stable
Python version: 3.8.4rc1
Operating system: posix

Command line: commix.py --url=********************************** --data=************************** --cookie=**************** PHPSESSID=b1e35028d3e0e07cff7fbb78a7816452

Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 906, in <module>
    filename = logs_filename_creation()
  File "main.py", line 349, in logs_filename_creation
    filename = logs.create_log_file(url, output_dir)
  File "logs.py", line 84, in create_log_file
    parts = url.split('//', 1)

**Comment by stasinopoulos** [comment]
Similar with https://github.com/commixproject/commix/issues/530
