### ISSUE TITLE
Failed to parse json payload

### ISSUE THREAD

**Issue by alpha1e0** [commixproject/commix#54]
Hi,

I found a issue when I input a json-formated payload like this:

`python commix.py -u http://xxxx --data '{"dir" :{"path": "."}}'`

when there exists whitespace before ":",  commix will not work correctly.

> commix/src/core/requests/parameters.py: 225

`value = re.findall(r'\:\"(.*)\"', parameter)`

the regular expression here would get nothing if there exists whitespace

I think, it should be

`value = re.findall(r'\:\s*\"(.*)\"', parameter)`

**Comment by stasinopoulos** [comment]
Thanks for the heads up. :)
