### ISSUE TITLE
[critical] global name _urllib is not defined

### ISSUE THREAD

**Issue by CINOAdam** [commixproject/commix#548]
I have the most recent version of x86 Kali running in a VM. When I tried to run:

commix -v 4 --tor --wizard -u mysite.com

I get [critical] global name _urllib is not defined

Thinking perhaps this was an issue with the Kali installation I cloned the repo, ran it directly with the same args, and got the exact same result.

The program appears to start the process by making the request successfully but after the HTML prints to console the error occurs and terminates.

Thank You!

**Comment by stasinopoulos** [comment]
Hey @CINOAdam , please try to re-run the commands using python 2.7.
