### ISSUE TITLE
Bug Report: Infinite Redirect Loop

### ISSUE THREAD

**Issue by init5-msft** [commixproject/commix#552]
## What's the problem (or question)?
I am testing commix against HTB's box "Fortune"
Syntax:
`./commix.py -u "http://10.10.10.127/select" --data="db=startrek" -H "Content-Type: application/x-www-form-urlencoded" --proxy="http://127.0.0.1:8080"`

It keeps resulting in the error:
`[critical] Infinite redirect loop detected.Please check all provided parameters and/or provide missing ones.`

This is weird because I can see the request response in Burp, and the web server is responding with HTTP 200, there are no redirects at all.

The POST request in question:
```
POST /select HTTP/1.1
Host: 10.10.10.127
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 11
Origin: http://10.10.10.127
Connection: close
Referer: http://10.10.10.127/
Upgrade-Insecure-Requests: 1

db=startrek
```

## What are the running context details?

* Installation method:  `git clone` 
* Client OS: `Kali Linux`
* Program version: `v3.2-dev#34` 
* Target OS: `OpenBSD` 
* Results of manual target assessment: Working payload `;whoami`

**Comment by stasinopoulos** [comment]
Hello @init5-msft, try to use `-r` to load the HTTP request from a file.

**Comment by init5-msft** [comment]
Hey @stasinopoulos 
I've just tried that and it gave me the exact same result. In Burp I can see 2 POST requests, both of which have a HTTP 200 response.

I tried the script against a different HTB that also has a command injection vulnerability and it worked perfect. Seems like something in the way the 1st web server responds throws off the script's behavior.

**Comment by shelld3v** [comment]
@stasinopoulos

Look at this code (from `src/core/requests/redirection.py`):

```python
  # Raise exception regarding infinite loop.
  except RuntimeError:
    err_msg = "Infinite redirect loop detected." 
    err_msg += "Please check all provided parameters and/or provide missing ones."
    print(settings.print_critical_msg(err_msg))
    raise SystemExit()
```

From what I found, the error for too many redirects is:

```
urllib.error.HTTPError: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
```
Which will be handled by:

```python
  # Raise exception regarding urllib2 HTTPError.
  except _urllib.error.HTTPError as err:
    err_msg = str(err).replace(": "," (")
    print(settings.print_critical_msg(err_msg + ")."))
    raise SystemExit()
```

Seem that it is returning the wrong error message for the real problem

**Comment by stasinopoulos** [comment]
@shelld3v that bug needs investigation, we must found a real case scenario (like the one provided by @init5-msft) in order to resolve the issue.
