### ISSUE TITLE
log file error

### ISSUE THREAD

**Issue by scblakely** [commixproject/commix#56]
Get a traceback when I try to run commix ...

`Traceback (most recent call last):
  File "commix.py", line 877, in <module>
    filename = logs_filename_creation()
  File "commix.py", line 108, in logs_filename_creation
    filename = logs.create_log_file(url, output_dir)
  File "/home/simon/commix/src/utils/logs.py", line 61, in create_log_file
    parts = url.split('//', 1)
AttributeError: 'NoneType' object has no attribute 'split'`

**Comment by stasinopoulos** [comment]
Hey, thanks for the heads up. This error has probably occurred due to lack of http/s on the target host (via --url/-u option). Could you please confirm?
