### ISSUE TITLE
/dev/null on Windows

### ISSUE THREAD

**Issue by VolkNwn** [commixproject/commix#59]
Hi, i try use with tor on win7, but has error:

>   File "\src\utils\requirments.py
> ", line 24, in do_check
>     null = open("/dev/null", "w")
> IOError: [Errno 2] No such file or directory: '/dev/null'
> 

Google told me fix:
```
import os
 null = open(os.devnull, "w")
```
After this;

>  Critical: HTTP Error 501: Tor is not an HTTP Proxy

But now Tor didn't use HTTP proxy, only socks5. Maybe.

Sorry, my english bad, first my post

**Comment by stasinopoulos** [comment]
Hey @VolkNwn, thanks for the bug report. I' ll check it out soon.

**Comment by stasinopoulos** [comment]
**TOR configuration (with privoxy).**
1. Install privoxy proxy.
`# apt-get install privoxy`

2. Enter the following line, in the bottom of the configuration file : `/etc/privoxy/config`.
`forward-socks5 / localhost:9050 .`

3. Restart privoxy service.
`# /etc/init.d/privoxy restart`

**Usage example:**

![screenshot from 2017-01-07 13-44-29](https://cloud.githubusercontent.com/assets/5289251/21741942/2000f21a-d4ed-11e6-8761-2a7e6fb57cf1.png)

**Comment by VolkNwn** [comment]
Yes, you were right. privoxy it really works. Tnx
