### ISSUE TITLE
Flag for traffic-file (-t) is not working: [critical] free variable 'info_msg' referenced before assignment in enclosing scope.

### ISSUE THREAD

**Issue by techn0tr0ll** [commixproject/commix#601]
During the execution of commix i encountered the problem, that the flag -t is not working.

The following command in the testbed environment is fine:
```
sudo python /usr/share/commix/commix.py --url="http://192.168.36.131/commix-testbed/scenarios/user-agent/ua(blind).php" --level=3 --proxy="http://127.0.0.1:8080/"           
                                               
[...]

[info] Checking connection to the target URL.           
[info] Setting the HTTP header User-Agent for tests.
[info] Testing the (results-based) classic command injection technique... (0.0%)
[...]
```

By adding the -t flag to log the output of the tool the following output is generated:
```
sudo python /usr/share/commix/commix.py --url="http://192.168.36.131/commix-testbed/scenarios/user-agent/ua(blind).php" --level=3 --proxy="http://127.0.0.1:8080/" -t test.txt

[...]

[info] Checking connection to the target URL.           
[critical] free variable 'info_msg' referenced before assignment in enclosing scope.
```
Tried with python 2.7 as well as python 3 - doesn't make a difference.

**Comment by stasinopoulos** [comment]
Hey @techn0tr0ll please update to the latest (dev) version -via git- and try again.

**Comment by techn0tr0ll** [comment]
mmhh ... that's weird 🤔 
i pulled the repo 2 days ago and did a fresh install ... 
the installed binary does not work, nevertheless, executing the py file inside of the repo works now 

thx for your quick support 👍
