### ISSUE TITLE
Doesnt work on kali 

### ISSUE THREAD

**Issue by obaskly1** [commixproject/commix#61]
![issue](https://cloud.githubusercontent.com/assets/24976394/21742736/ac8a5fda-d4f4-11e6-9467-87383e83e323.jpg)

**Comment by stasinopoulos** [comment]
Hey @obaskly1, get the latest **dev** version of commix by cloning the git repository: `git clone https://github.com/commixproject/commix.git commix` or just use the package manager to update to the latest **stable** version: `apt-get upgrade commix`.
