### ISSUE TITLE
Bug: DVWA Command Injection is not detected

### ISSUE THREAD

**Issue by merlinwoff** [commixproject/commix#625]
## What's the problem (or question)?
I am training pentesting with the XVWA and the DVWA web applications. In the XVWA, commix successfully detects the os command injection:
```bash
$ python2 /opt/commix/commix.py -u http://xvwa.example.com/xvwa/vulnerabilities/cmdi/?target=
[info] Resolving hostname 'xvwa.example.com'.
[info] Checking connection to the target URL.
[warning] Heuristics have failed to identify target application.
[warning] The provided value for GET parameter 'target' is empty. Use valid values to run properly.
[info] Setting the GET parameter 'target' for tests.
[info] Testing the (results-based) classic command injection technique.
[info] The GET parameter 'target' seems injectable via (results-based) classic command injection technique.
       |_ ;echo MERYYF$((25+7))$(echo MERYYF)MERYYF
```
In the DVWA, the command injection (which is very simple) is not detected at all. Only difference is, that there it is a POST request:
```bash
$ python2 /opt/commix/commix.py -u http://dvwa.example.com/vulnerabilities/exec/  --data="ip=192.168.1.1&Submit=Submit"
[info] Resolving hostname 'dvwa.example.com'.
[info] Checking connection to the target URL.
[warning] Heuristics have failed to identify target application.
[info] Setting the POST parameter 'ip' for tests.
[info] Testing the (results-based) classic command injection technique.
[info] Testing the (results-based) dynamic code evaluation technique.
[info] Testing the (blind) time-based command injection technique.

```

## Do you have an idea for a solution?
Maybe there is a problem testing POST requests with the (results-based) classic command injection technique.

## How can we reproduce the issue?
You can install the official Damn Vulnerable Web Application (DVWA) hacker page from here:
https://dvwa.co.uk/

## What are the running context details?
* Installation method: git clone
* Client OS: CentOS 8
* Program version: v3.2-dev#93
* Target OS (e.g. `Linux (Debian)`): CentOS 8
* Command injection techniques found by commix: classic (results-based)
* Results of manual target assessment: `;echo RNMEYYsssss` works and outputs 'RNMEYYsssss'

**Comment by stasinopoulos** [comment]
Hello,  @merlinwoff,

I used the Damn Vulnerable Web Application Docker container from https://hub.docker.com/r/vulnerables/web-dvwa and the result was the following:

![Screenshot 2021-04-04 at 9 40 21 AM](https://user-images.githubusercontent.com/5289251/113500825-c9657780-9529-11eb-99e8-29d218d09b29.png)

**Comment by merlinwoff** [comment]
I forgot to add the cookies! Thank you!

**Comment by merlinwoff** [comment]
> 
> 
> Hello, @merlinwoff,
> 
> I used the Damn Vulnerable Web Application Docker container from https://hub.docker.com/r/vulnerables/web-dvwa and the result was the following:
> 
> ![Screenshot 2021-04-04 at 9 40 21 AM](https://user-images.githubusercontent.com/5289251/113500825-c9657780-9529-11eb-99e8-29d218d09b29.png)

Correction: I tried the add the cookie but using the --headers instead of --cookie:
```bash
python3 /opt/commix/commix.py -u "http://dvwa.example.com" --flush-session --offline --batch --headers="Cookie:security=low" --data="ip=&Submit=Submit"
```

And this does not return the wanted results. But it works when using the `--cookie` parameter.
Is this a bug or any specific reason why this does not work?

**Comment by stasinopoulos** [comment]
By default, the `--cookie ` parameter can be used for parsing cookie values. You can alse use to `-r` option for parsing a an HTTP request from a file (i.e. fron burp). 

BTW what you entered on your command does not specify the `PHPSESSID` value.
