### ISSUE TITLE
Bug Report: It seems that the 'FILE_NAME' file, does not exist

### ISSUE THREAD

**Issue by ibrotutic** [commixproject/commix#627]
## What's the problem (or question)?

I have a file with contents that I got from burp suite that looks something like this (full contents in screen capture below).
GET /order.php?order=2 HTTP/1.1
Host: IP
User-Agent: ...

I am attempting to run `commix -r commix.txt` from the same directory as the file `commix.txt`. I can do `cat commix.txt` and the contents are show in the shell. Any file that I pass into the -r argument gets the `file does not exist` error. I know that this webpage is vulnerable to command injection as it has a search bar where I can enter arbitrary UNIX commands and get the output. 

## How can we reproduce the issue?

1. Have a file.
2. Run commix -r filename
3. File not found error occurs.
4.

## What are the running context details?

* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`): apt-get
* Client OS (e.g. `Linux (Ubuntu)`): Kali Linux
* Program version (`python commix.py --version` or `commix --version` depending on installation):  v3.1-stable
* Target OS (e.g. `Linux (Debian)`): Ubuntu
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`):
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works):
* Relevant console output (if any):
* Exception traceback (if any):
* **
![image](https://user-images.githubusercontent.com/38231541/114108133-0ddd7400-9898-11eb-80e4-525ee7fea302.png)
**

**Comment by stasinopoulos** [comment]
Hey @ibrotutic  please update to the latest (dev) version -via git- and try again.

**Comment by ibrotutic** [comment]
@stasinopoulos Thanks for the response. Looks like using the full path worked, but I get a "Critical 13" error. I will try out the dev build and see if that works any better.

![image](https://user-images.githubusercontent.com/38231541/114253227-fa510c80-996e-11eb-95bd-74402257012f.png)

**Comment by stasinopoulos** [comment]
To get an overview of commix available options, switches and/or basic ideas on how to use commix, check the [wiki](https://github.com/commixproject/commix/wiki).
