### ISSUE TITLE
ImportError on Windows 7

### ISSUE THREAD

**Issue by wisahmed** [commixproject/commix#64]
![commix](https://cloud.githubusercontent.com/assets/20966363/23052627/ca9ecde8-f4f8-11e6-8329-4f039e3cbe98.PNG)

Hey,
Is there something i need to do before using commix on windows 7. Im very new to this .. and first command i tried itself is an error.

Thanks,
WISAM

**Comment by stasinopoulos** [comment]
Hello, what version of commix do you use? Please, download the latest, and check if the error still exists.

**Comment by wisahmed** [comment]
it is the latest version. I downloaded it just before i posted error.

**Comment by stasinopoulos** [comment]
Sorry, but I can't reproduce the error in the latest version (v1.8-dev#8). 
![screenshot from 2017-02-17 18-54-44](https://cloud.githubusercontent.com/assets/5289251/23074788/b326092a-f542-11e6-8da9-3825036d0c60.png)

**Comment by wisahmed** [comment]
![commix1](https://cloud.githubusercontent.com/assets/20966363/23110123/c493ea66-f744-11e6-8d4a-584f2e13be60.PNG)

**Comment by wisahmed** [comment]
hey but this is what im getting now. 
i have python installed in my machine 
but when i tried to install pyreadline onto my machine, it doesnt seem to detect python in my system

**Comment by stasinopoulos** [comment]
Try to install the "pyreadline-2.1.win32.exe" from https://pypi.python.org/pypi/pyreadline
