### ISSUE TITLE
How to read tmp file from target?

### ISSUE THREAD

**Issue by vnvyvu** [commixproject/commix#643]
## What's the problem (or question)?

How Commix read tmp file? How to do this without Commix? I am playing with Commix-Testbed. I have searched but no answer. Thank you!

`commix --url="***/scenarios/regular/GET/blind.php?addr=" --technique=f --skip-waf --skip-calc`

blind.php

```
$addr = $_GET['addr'];
if(isset($addr)){
    if( stristr(php_uname('s'), 'Windows NT')){
       # Windows-based command execution.
       echo exec('ping '.$addr, $output, $return);
    } else {
       # Unix-based command execution.
       exec("/bin/ping -c 4 ".$addr, $output, $return);
    }
    if (!$return) {
       echo "The ip ".$addr." seems to be up and running!";
    } else {
       echo "The ip ".$addr." seems to be down!";
    }
}
```

**Comment by stasinopoulos** [comment]
Hey take a look here https://link.springer.com/article/10.1007/s10207-018-0399-z
