### ISSUE TITLE
Preg_replace.php

### ISSUE THREAD

**Issue by vnvyvu** [commixproject/commix#647]
## What's the problem (or question)?

`http://***/scenarios/regular/GET/preg_replace.php?replace=/Hello.*/e&with=exec("ls")`
The below command doesn't work:

`commix --url="http://***/scenarios/regular/GET/preg_replace.php?replace=/Hello.*/e&with=Bye" --skip="replace" --prefix="exec('" --suffix="')" --skip-waf`

![image](https://user-images.githubusercontent.com/22812601/122641163-a6606200-d12d-11eb-9929-f2191e76e9b7.png)

temporarily, i use `.{0,}` instead of `.*`

**Comment by stasinopoulos** [comment]
![Screenshot 2021-06-19 at 6 09 03 PM](https://user-images.githubusercontent.com/5289251/122646748-7d3dd280-d129-11eb-88c9-2011e3516c55.png)
