### ISSUE TITLE
When using a file, stops on retry instead of going to the next url.

### ISSUE THREAD

**Issue by gprime31** [commixproject/commix#668]
When using a file commix stops on timeout instead of moving on to the next url.

![Screenshot_20210817-173649_JuiceSSH](https://user-images.githubusercontent.com/44535257/129804265-708f7029-0b86-4e4c-8682-c58795cc0cb5.jpg)

**Comment by stasinopoulos** [comment]
Kindly provide me with more info regarding that issue.

**Comment by gprime31** [comment]
When using the -m command if a url times out it stops the program instead of morning on the the next url in the list.

**Comment by gprime31** [comment]
Tried with different lists ex:

List 1. https://site.com/?param=value
etc...
List 2. site.com/?param=value
etc...
List 3.  https://site.com/
etc...
Tried with all combinations of ^^^ same result.

**Comment by stasinopoulos** [comment]
Thanks for the heads up, i'll check it out.
