### ISSUE TITLE
Difference between standard Commix and Commix-Master ?

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#670]
Hello my question is what are the key differences between the commix that is provided with Kali and others and the one that we need to update and use for OS command injections?

**Comment by stasinopoulos** [comment]
Hello, Kali uses the **stable** versions of commix. 
By cloning the official Git repository you are able to update commix at any time to the latest development version (which is not stable).

**Comment by Anthonymcqueen21** [comment]
Okay thank you for clarification
