### ISSUE TITLE
Unable to use commix ?

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#672]
Hello for some reason i am unable to use to commix that comes standard even if i want to update it something that simple and i get this from my terminal ? Also why does it keep saying i have not updated it even when i used to log on and use the tool i have to update manually constantly ? did i just lose my commix tool and do i need to clone another one ?...Any help with this issue would be appreciated thank you.
![image](https://user-images.githubusercontent.com/23253941/133845170-05f63640-6afc-459d-a73c-155bc84fe73e.png)

**Comment by stasinopoulos** [comment]
On Kali you can't use "--update" flag. 

Alternatively you can download commix by cloning the official Git repository : 
`git clone https://github.com/commixproject/commix.git commix`

**Comment by Anthonymcqueen21** [comment]
So is this clone repository the same thing as the default commix that was standard with Kali-Linux ?

**Comment by Anthonymcqueen21** [comment]
Is there anyway to get my original Commix tool that came default with Kali-Linux working again rather than alternatives ?
