### ISSUE TITLE
Feature Request: Retry option

### ISSUE THREAD

**Issue by r3pek** [commixproject/commix#69]
I was doing a Shell injection testing (that i know it's vulnerable) and for some reason the connection get's "terminated" after a while. So, my suggestion is to add a retry option for a number of retry attempts to connect to the target, or even unlimited retries.

**Comment by stasinopoulos** [comment]
Done! (https://github.com/commixproject/commix/commit/db0c78f4c3d82c48168cbb8e01ec2a51d4e041b7)
