### ISSUE TITLE
Why so slow ?

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#695]
Why is commix so slow even when it's updated, everything is working well for the DVWA and Test-bed applications. But when it comes to live hunting for testing the process is very and i mean very slow, what could be the issue. Even when i do a simple test scan, the process takes upwards of 30mins to do a simple scan without many parameters added to it.

**Comment by stasinopoulos** [comment]
The scanning speed time depends on the application you are checking.
