### ISSUE TITLE
Commix Network Unreachable 

### ISSUE THREAD

**Issue by webkodex** [commixproject/commix#70]
Hi, i cannot run commix in latest version of Kali as of now, i tried a vm with host only adapter & am getting this network unreachable error, kindly suggest if there is a fix.
Kali Version
lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling

root@kali:~# commix
[x] Critical: Network is unreachable.

Regards
web..

**Comment by stasinopoulos** [comment]
Hello, what version of commix do you use and what parameters did you provide? 

**Note:** Get the latest **dev** version of commix by cloning the git repository: `git clone https://github.com/commixproject/commix.git commix` or just use the package manager to update to the latest **stable** version: `apt-get upgrade commix`.

**Comment by webkodex** [comment]
Hi am using latest version I think so that comes with newest Kali Linux, I tried upgrade method but am getting 404. I will try to git clone..
Thank you..
