### ISSUE TITLE
Dont know if this is a issue but i had to ask.

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#710]
Hello i am not sure if this is not an issue or is it just how Commix works but even with the latest update i use it for simple testing. Once i do a simple "INJECT_HERE" just to see what comes about on my target, it tests like this it keeps going and going. But it works fine when it comes to the commix-testbed and does not have this when doing practice tests.

**based) classic command injection technique. (24.4%) 
[info] Testing the (results-based) classic command injection technique. (24.4%) 
[info] Testing the (results-based) classic command injection technique. (24.4%) 
[info] Testing the (results-based) classic command injection technique. (24.5%) 
[info] Testing the (results-based) classic command injection technique. (24.5%) 
[info] Testing the (results-based) classic command injection technique. (24.6%) 
[info] Testing the (results-based) classic command injection technique. (24.6%) 
[info] Testing the (results-based) classic command injection technique. (24.6%) 
[info] Testing the (results-based) classic command injection technique. (24.7%) 
[info] Testing the (results-based) classic command injection technique... (24.8%) 
[info] Testing the (results-based) classic command injection technique. (24.8%) 
[info] Testing the (results-based) classic command injection technique... (24.9%) 
[info] Testing the (results-based) classic command injection technique. (24.9%) 
[info] Testing the (results-based) classic command injection technique. (24.9%) 
[info] Testing the (results-based) classic command injection technique. (25.0%) 
[info] Testing the (results-based) classic command injection technique. (25.0%) 
[info] Testing the (results-based) classic command injection technique. (25.1%) 
[info] Testing the (results-based) classic command injection technique. (25.1%) 
[info] Testing the (results-based) classic command injection technique. (25.1%) 
[info] Testing the (results-based) classic command injection technique. (25.2%) 
[info] Testing the (results-based) classic command injection technique. (25.2%) 
[info] Testing the (results-based) classic command injection technique... (25.3%) 
[info] Testing the (results-based) classic command injection technique. (25.3%) 
[info] Testing the (results-based) classic command injection technique... (25.4%) 
[info] Testing the (results-based) classic command injection technique. (25.4%) 
[info] Testing the (results-based) classic command injection technique. (25.5%) 
[info] Testing the (results-based) classic command injection technique. (25.5%) 
[info] Testing the (results-based) classic command injection technique. (25.6%) 
[info] Testing the (results-based) classic command injection technique. (25.6%) 
[info] Testing the (results-based) classic command injection technique. (25.6%) 
[info] Testing the (results-based) classic command injection technique. (25.7%) 
[info] Testing the (results-based) classic command injection technique. (25.7%)** 

Just testing for a simple command injection technique, and it tests like this ?

**Comment by stasinopoulos** [comment]
The scanning speed time depends on the application you are checking.
