### ISSUE TITLE
Feature Request: Inject in URL parameter of POST requests

### ISSUE THREAD

**Issue by palaziv** [commixproject/commix#711]
Hello,

I experience the same problem as described here: https://github.com/commixproject/commix/issues/42. I try to test the URL parameter "foo" in the following example HTTP POST request:

POST /whatever/bla.asp?**foo**=bar
Host: example.com
Content-Type: application/x-www-form-urlencoded
[...]

val1=1&val2=2&val3=3

Now when I try to run commix like so _python3 commix.py --url "https://example.com/whatever/bla.asp?foo=bar*" --data="val1=1&val2=2&val3=3" -p foo_ commix refuses to test the "foo" parameter with the message "[warning] Skipping tests for the provided parameter 'foo' as it is not part of the POST data."

Is it possible to force commix to test that parameter anyway?

**Comment by stasinopoulos** [comment]
Thanks for heads up, i ll check it out soon in order to make commix to inject URL parameters in POST requests.
