### ISSUE TITLE
Trouble with injection in the header User-Agent

### ISSUE THREAD

**Issue by prince74igor** [commixproject/commix#717]
Hi there.

## What's the problem (or question)?
Following commix guide to start an injection in the header User-Agent we should use the construction:
`--user-agent=AGENT`

When we use it:
1.
**Value**
`--user-agent="test*"`
**Input**
`python2 /usr/share/commix/commix.py -u http://<MY_IP>:4800/device-information --data='threeDSMethodData=<@base64>{"threeDSMethodNotificationURL":"http://<MY_IP>:7778/ThreeDSServer/methodNotificationUrl.jsp?orderId=46993310728AA4DE","threeDSServerTransID":"ea89674d-08da-45fc-a519-9937087db9a0"}<@/base64>' --proxy=http://127.0.0.1:8080 -v 2  --headers='user-agent: test*'`
we receive:
**Output**
```
POST /device-information HTTP/1.1
Content-Length: 270
Accept-Encoding: gzip, deflate
Connection: close
Accept: */*
User-Agent: test*
Host: <MY_IP>:4800
Content-Type: application/x-www-form-urlencoded
```
As you can see, commix does not use this header to properly perform the injection.

We tried these options too:
2. 
**Value**
`--headers='user-agent: test*'`
**Input**
`python2 /usr/share/commix/commix.py -u http://<MY_IP>:4800/device-information --data='threeDSMethodData=<@base64>{"threeDSMethodNotificationURL":"http://<MY_IP>:7778/ThreeDSServer/methodNotificationUrl.jsp?orderId=46993310728AA4DE","threeDSServerTransID":"ea89674d-08da-45fc-a519-9937087db9a0"}<@/base64>' --proxy=http://127.0.0.1:8080 -v 2 --headers="user-agent:test*"`
**Output**
```
POST /device-information HTTP/1.1
Content-Length: 223
Accept-Encoding: gzip, deflate
Connection: close
Accept: */*
User-Agent: &echo BNFMAN$((56+88))$(echo BNFMAN)BNFMAN
Host: <MY_IP>:4800
Content-Type: application/x-www-form-urlencoded
```
It seems all is fine.

3. 
**Value**
`--user-agent="fsd" --headers='user-agent: test*'`
**Input**
`python2 /usr/share/commix/commix.py -u http://<MY_IP>:4800/device-information --data='threeDSMethodData=<@base64>{"threeDSMethodNotificationURL":"http://<MY_IP>:7778/ThreeDSServer/methodNotificationUrl.jsp?orderId=46993310728AA4DE","threeDSServerTransID":"ea89674d-08da-45fc-a519-9937087db9a0"}<@/base64>' --proxy=http://127.0.0.1:8080 -v 2 --user-agent="fsd" --headers="User-Agent:test*"`
**Output**
```
POST /device-information HTTP/1.1
Content-Length: 223
Accept-Encoding: gzip, deflate
Connection: close
Accept: */*
User-Agent: echo MQCLXU$((94+73))$(echo MQCLXU)MQCLXU
Host: <MY_IP>:4800
Content-Type: application/x-www-form-urlencoded
```
It seems all is fine too.

## Do you have an idea for a solution?
Shall we use values from options 2 or 3 if we want to use header User-Agent should now? Shall we?
I think it make sense to fix of using this header with the value from option 1 to match commix help.

First header User-Agent seems work properly, but there is 2 headers User-Agent now.
It does not seem to will work fine for a webserver.

This behavior is typical for all of others main headers witch we are using:
--referer="fsd*"
--user-agent="fsd*"
--cookie="fsd*"

## How can we reproduce the issue?
See information above.

## What are the running context details?
* Client OS (e.g. `Linux (Ubuntu)`):  Linux kali 5.14.0-kali4-amd64 #1 SMP Debian 5.14.16-1kali1 (2021-11-05) x86_64 GNU/Linux
* Python version: 2.7.18
* Program version (`python commix.py --version` or `commix --version` depending on installation): Version: v3.3-stable
* Target OS (e.g. `Linux (Debian)`): Windows server 2016
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`): see above.
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works): see above.
* Relevant console output (if any): see above.
* Exception traceback (if any): see above.

Thank you for spending time.

**Comment by stasinopoulos** [comment]
Hello @prince74igor thanks for your comments. 
Please give a shot with the following parameter: `-p user-agent`

**Comment by stasinopoulos** [comment]
Hello @prince74igor thanks for your comments.
Please update commix to the latest `dev` version and give a shot with the following parameter: `-p user-agent`.

**Comment by prince74igor** [comment]
Hi, @stasinopoulos.

We tested with `-p`, but the problem is that this applies only to basic headers: `Host`, `User-agent`, `Referer`.
When applying an injection through `*` we noticed or missed injections. In this connection, the question. Is this normal behavior? Will the missed payloads be applied in subsequent questions or will they be lost? Although, we swept the duplication of fields when working with some Headers. Is it OK?
We have prepared summary tables with the results of our research. Please read and inform us about the best practices for use.

![image](https://user-images.githubusercontent.com/94838692/147201855-02487587-bee0-4a97-988c-99459f26f9dd.png)
![image](https://user-images.githubusercontent.com/94838692/147201709-8018a8f3-3883-4512-a4f0-b7272ae58ca5.png)
![image](https://user-images.githubusercontent.com/94838692/147201722-7e4b6a24-eec1-43e5-9c18-827f61b0ff11.png)
![image](https://user-images.githubusercontent.com/94838692/147201741-e65c128c-8b46-4004-935a-af871a856fbf.png)
![image](https://user-images.githubusercontent.com/94838692/147201756-dd01e704-b3a6-40db-ade4-fd372092f0b7.png)

**Comment by stasinopoulos** [comment]
Fixed https://github.com/commixproject/commix/commit/1232bf63dc9c52aa31fe0ded5e0dc06a1407f77e
