### ISSUE TITLE
Still having updating issues...

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#725]
![Screenshot from 2021-12-22 16-05-47](https://user-images.githubusercontent.com/23253941/147168669-1354cd25-22ef-40e0-ae49-0d0fbe05f7e2.png)

Commix already exists in Kali for me and the directory, so whenever i try to update i get this ongoing issue i am having with this tool. I know i see how to update but when i do this still gives me issues and i do not know why. Your tool is amazing when it comes to the test bed but when testing against real world applications comes issues very slow for example even for a simple url test.

**Comment by stasinopoulos** [comment]
Similar with https://github.com/commixproject/commix/issues/672, https://github.com/commixproject/commix/issues/638 and https://github.com/commixproject/commix/issues/695 please **don't spam** with same topics again and again.

**Comment by Anthonymcqueen21** [comment]
Really dude i am not spamming anything I am just asking for help regarding the issues i am having with your tool, and honestly you have not helped at all.
