### ISSUE TITLE
Why this problem ?

### ISSUE THREAD

**Issue by webideveli** [commixproject/commix#730]
[x] Critical: URL can't contain control characters. '/login?username=\nstr=$(echo%20HHSHOV)\nstr1=$(expr%20length%20"$str")\nif%20[%201%20!=%20$str1%20]\nthen%20sleep%200\nelse%20sleep%201\nfi%20&password=<redacted>' (found at least '\n').

**Comment by stasinopoulos** [comment]
Hello @webideveli and thanks for that bug report.
Kindly provide more information (i.e. version of commix, provided commands etc) on that issue, in order to understand the problem.

**Comment by stasinopoulos** [comment]
Hello @webideveli and thanks for that bug report.
Kindly provide me with more information (i.e. version of commix, provided commands etc) regarding that issue, in order to understand the problem.

**Comment by webideveli** [comment]
![mam](https://user-images.githubusercontent.com/46009592/149665451-1fb2e4b4-799c-410a-9514-eb8f4a002fa4.PNG)
![prob](https://user-images.githubusercontent.com/46009592/149665453-249f4fc2-a1d6-4067-92d0-e974036549ec.PNG)
![right](https://user-images.githubusercontent.com/46009592/149665455-c7565295-927d-4264-a3b1-5f389b2edf4b.PNG)
![iia](https://user-images.githubusercontent.com/46009592/149665502-b8cb70de-f96c-4318-ac89-622dc87d6d30.PNG)

**Comment by webideveli** [comment]
Any help ?

**Comment by stasinopoulos** [comment]
I' ll check it out and push a relevant fix.

**Comment by stasinopoulos** [comment]
I' ll check it out and i'll push a relevant patch.

**Comment by webideveli** [comment]
How long will it take for that, thanks.
