### ISSUE TITLE
Can't establish connection with the Tor SOCKS proxy.

### ISSUE THREAD

**Issue by 6kemb0bani** [commixproject/commix#731]
Error while using `--tor` and `--tor-check`

`[info] Testing Tor SOCKS proxy settings (127.0.0.1:8118). [critical] Can't establish connection with the Tor SOCKS proxy. Please make sure that you have Tor installed and running so you could successfully use switch '--tor'.`

My torcc settings have `Socks4Proxy 127.0.0.1:8118`
https://check.torproject.org/ is working correctly.

**Comment by stasinopoulos** [comment]
Hello @6kemb0bani and thanks for that bug report.
Kindly provide me with more information (i.e. version of commix, provided commands etc) regarding that issue, in order to understand the problem.

**Comment by 6kemb0bani** [comment]
I simply run `commix.py -r ***** --tor`
commix Version: v3.4-dev#25
Not using a bridge or a proxy

**Comment by stasinopoulos** [comment]
Give a try with Tor bundle installed and setup (or Tor and Privoxy).
