### ISSUE TITLE
Asterisk escape 

### ISSUE THREAD

**Issue by Suselz** [commixproject/commix#736]
Hello.
## What's the problem (or question)?
My POST\GET request already contain asterisk symbol ("*") in CSRF field. 
Commix defines that symbol as an injection point and send error: 
 
 ```You specified more than one injection markers.```  
 
If I remove that those characters in request then the query becomes invalid.
How can I escape asterisk symbol in request or change injection-point symbol in commix?
## What i tried 

* urlencode asterisk symbol in request (replace ```*``` to ```%2a``` ) and stay injection-point by asterisk symbol (```*```) \
Result: error ```You specified more than one injection markers.``` 

* urlencode asterisk symbol in request (replace ```*``` to ```%2a``` ) and stay injection-point by tag ```INJECT_HERE``` \
Result: error ```You specified more than one injection markers.``` 

* urlencode asterisk symbol in request (replace ```*``` to ```%2a``` ) and stay injection-point by flag ```-p``` \
Result: error  ```You specified more than one injection markers.``` 

* find related to this case issue on GitHub  
Result: [#452](https://github.com/commixproject/commix/issues/452), [#453](https://github.com/commixproject/commix/issues/453)

## Do you have an idea for a solution?
In my opinion, you can solve the problem in the following ways:
* Add user-defined injection-tag feature 
* Do not use construction ```%2a``` (urlencode asterisk) as injection tag
* Do not check asterisk symbol in request if user stay injection-point by flag ```-p```

## How can we reproduce the issue?
Try simple request to any resource, where request contain asterisk symbol. \
For example:
```
python2 /usr/share/commix/commix.py -u http://127.0.0.1:81/bWAPP/htmli_post.php --data="firstname=asd*&lastname=asd%2a&form=submit%2a" --level=3 --batch -v 2 -p "firstname"
```

## What are the running context details?
I tried last stable version and last dev version (the result are the same)

* commix v3.3-stable
    * Installation method: `apt-get`
    * Client OS: `Linux (Kali Linux)`
    * Program version: `v3.3-stable`
    * Used python: `python 2.7.18`
    * Target OS: any

* commix v3.4-dev#55
    * Installation method: `git clone`
    * Client OS: `Linux (Kali Linux)`
    * Program version: `v3.4-dev#55`
    * Used python: `python 3.9.9`
    * Target OS: any

**Comment by stasinopoulos** [comment]
@Suselz thanks for your comments 👍  
I'll check it out soon :)

**Comment by stasinopoulos** [comment]
![3 4-dev#62](https://user-images.githubusercontent.com/5289251/151916504-919edb8f-bc8d-48a7-b0fc-549c2191ff32.png)

**Comment by Suselz** [comment]
@stasinopoulos, thanks for fix!
Works great.
