### ISSUE TITLE
How to stay injection-point into custom header-param

### ISSUE THREAD

**Issue by Suselz** [commixproject/commix#739]
Hello again.
## What's the problem (or question)?
*Question №1:*

How can i stay injection-point into custom header-param?

*Question №2:*

Is it normal for a commix to substitute patterns into a parameter by removing the value, rather than substituting into the end of the value? Are built-in patterns intended for this kind of use? 

## What i tried 

* add cookie-params by flag `--headers` and  stay injection-point by asterisk symbol (`*`)

Example:

```
python2 ./commix.py -u http://192.168.75.69:81/bWAPP/test.php  --data='target=www.nsa.gov&form=submit' -v 2 --headers="Test-param: test-value*" --batch
```

Result: Erased header value. Injecting into value without data.
```
[debug] Generating payload for the injection.
[payload] &echo%20CLJUCJ$((66%2B92))$(echo%20CLJUCJ)CLJUCJ
[traffic] HTTP request [#10]:
POST /bWAPP/test.php HTTP/1.1
Content-Length: 30
Accept-Encoding: gzip, deflate
Connection: close
Test-Param: &echo CLJUCJ$((66+92))$(echo CLJUCJ)CLJUCJ
Accept: */*
User-Agent: commix/v3.3-stable (https://commixproject.com)
Host: 192.168.75.69:81
Content-Type: application/x-www-form-urlencoded

target=www.nsa.gov&form=submit
```

* add cookie-params by flag `--headers` and stay injection-point by flag `-p`

Example:

```
 python2 ./commix.py -u http://192.168.75.69:81/bWAPP/test.php  --data='target=www.nsa.gov&form=submit'--headers="Test-param: test-value" -v 2 --batch --skip-waf -p 'Test-param'
```

Result: error `Skipping tests for the provided parameter 'Test-param' as it is not part of the POST data.`

## How can we reproduce the issue?
Examples of requests are presented in the previous paragraph. 

## What are the running context details?
I tried last stable version and last dev version (the result are the same)

* commix v3.3-stable
    * Installation method: `apt-get`
    * Client OS: `Linux (Kali Linux)`
    * Program version: `v3.3-stable`
    * Used python: `python 2.7.18`
    * Target OS: any

* commix v3.4-dev#63
    * Installation method: `git clone`
    * Client OS: `Linux (Kali Linux)`
    * Program version: `v3.4-dev#63`
    * Used python: `python 3.9.9`
    * Target OS: any

**Comment by stasinopoulos** [comment]
Similar with https://github.com/commixproject/commix/issues/717

**Comment by stasinopoulos** [comment]
Fixed https://github.com/commixproject/commix/commit/1232bf63dc9c52aa31fe0ded5e0dc06a1407f77e
