### ISSUE TITLE
Solucion utf-8 commix@stasinopoulos

### ISSUE THREAD

**Issue by c0d3r17** [commixproject/commix#742]
@stasinopoulos 
![c4](https://user-images.githubusercontent.com/49366477/125158306-d780f080-e135-11eb-8c80-dd515588621b.png)

_Originally posted by @6kemb0bani in https://github.com/commixproject/commix/issues/649#issuecomment-877603717_

**Comment by c0d3r17** [comment]
Luego hice otra prueba descargue commix desde github v3.4 y aplique lo mismo, pero aqui ya no es encoding, sino "--codec cp1251" y funciono correctamente en un kali 2021
![Captura](https://user-images.githubusercontent.com/47430306/156408970-27dd6cc7-6322-4469-8058-b23e7ea8916c.PNG)

**Comment by stasinopoulos** [comment]
Hello @c0d3r17, kindly write in English. Thanks 🙂
