### ISSUE TITLE
Feature Request: Crawl forms

### ISSUE THREAD

**Issue by arnoldasr** [commixproject/commix#743]
## What's the problem (or question)?
Would it be possible to implement form crawling, just like sqlmap does?
https://github.com/sqlmapproject/sqlmap/blob/master/lib/utils/crawler.py

## What are the running context details?
Commix works great on crawling and finding simple parameters, but in some cases, the form itself can have a command injection and would need to be crawled also.

**Comment by stasinopoulos** [comment]
Hello @arnoldasr fyi currently commix is able to collect only GET links. kindly provide me with an example regarding what you proposing.

**Comment by stasinopoulos** [comment]
Hello @arnoldasr fyi currently commix is able to collect only GET links. kindly provide me with an example regarding what do you propose.
