### ISSUE TITLE
404 Error on Response with Status Code 302 Found (Redirect)

### ISSUE THREAD

**Issue by rbrown81** [commixproject/commix#75]
Big fan of Commix.  When working on an assessment today, I decided to push a request through Commix.  Seems the application has a bug in it because Commix is identifying an HTTP response with a 302 redirect status code, as a 404 not found. Attached some screenshots.  There work for a client therefore I stripped out identifying information such as the host, a redirect parameter, and the location response header.

![commix_ss](https://cloud.githubusercontent.com/assets/25639942/25545504/28901266-2c2d-11e7-8acd-e04ec212aed8.jpg)
![req_burp](https://cloud.githubusercontent.com/assets/25639942/25545514/2ee291ca-2c2d-11e7-9725-8bd17a3184f5.jpg)
![resp_burp](https://cloud.githubusercontent.com/assets/25639942/25545516/3054ff20-2c2d-11e7-9993-3e77fed01725.jpg)

**Comment by stasinopoulos** [comment]
Hello @rbrown81 and thanks for the issue.
Could you please update Commix to the latest version and try this request again? 
If the problem still exists, please let me know.

**Comment by stasinopoulos** [comment]
I would close this one down due to lack of information.
