### ISSUE TITLE
[critical] Connection aborted. 

### ISSUE THREAD

**Issue by MajorD4m4ge** [commixproject/commix#754]
## What's the problem (or question)?
Commix issues a request to the server based off a save request.  The server responds, but commix aborts the connection.  The tests have been through a proxy as well, and the responses match legitimate responses.

Debug info:
```
[info] Parsing HTTP request using the 'r.txt' file.
[debug] Setting the HTTP timeout.
[debug] Fetching random HTTP User-Agent header.
[info] The fetched random HTTP User-Agent header value is 'mozilla/3.0 (Windows NT 6.1; rv:2.0.1) Gecko/20100101 Firefox/5.0.1'.
[debug] Setting the HTTP User-Agent header.
[debug] Creating HTTPS requests opener object.
[info] Testing connection to the target URL.
[traffic] HTTP request [#1]:
POST /<REDACTED> HTTP/1.1
Content-Length: 106
Host: 192.168.1.1
User-Agent: mozilla/3.0 (Windows NT 6.1; rv:2.0.1) Gecko/20100101 Firefox/5.0.1
Referer: https://192.168.1.1/
Cookie:<snip>
Accept: application/json, text/plain, */*
Sec-Ch-Ua: "(Not(A:Brand";v="8", "Chromium";v="99"
Content-Type: application/x-www-form-urlencoded
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Origin: https://192.168.1.1
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: close

token=<snip>
[traffic] HTTP response [#1] (200):
Strict-Transport-Security: max-age=63072000
Content-Length: 0
Connection: close
Date: Sun, 27 Mar 2022 09:57:01 GMT
URI: https://192.168.1.1/<REDACTED>.cgi


[critical] Connection aborted.
```

----
Running fastest MacOS
Version of commix: v3.5-dev#14

**Comment by stasinopoulos** [comment]
hello @MajorD4m4ge kindly provide me with the `r.txt` file, also try to use `--force-ssl` flag.

**Comment by MajorD4m4ge** [comment]
I did try --force-ssl and other options and even tried it via command line, not request.

➜  commix git:(master) python3 commix.py --data "token=<snip>%2f6ni4hxA3gZQ%3D%3D=<snip>" -u https://192.168.1.1/<snip>.cgi --method=POST -p "<snip>%2f6ni4hxA3gZQ%3D%3D" --force-ssl --proxy=http://127.0.0.1:8080 --cookie="<snip>=03802d095c9db53814cef5f79f10cc38"  --random-agent -v 4


Below is request file:

POST /<snip>.cgi HTTP/1.1
Host: 192.168.1.1
Cookie: <snip>=966ac21c400c0c85cc232192dc29b822
Content-Length: 106
Sec-Ch-Ua: "(Not(A:Brand";v="8", "Chromium";v="99"
Accept: application/json, text/plain, */*
Content-Type: application/x-www-form-urlencoded
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
Sec-Ch-Ua-Platform: "macOS"
Origin: https://192.168.1.1
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://192.168.1.1/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: close

token=<snip>&<snip>VWQ%3D%3D=on

**Comment by stasinopoulos** [comment]
I used the exact same example against commix-testbed and it seems work fine:

![Screenshot 2022-03-27 at 4 09 17 PM](https://user-images.githubusercontent.com/5289251/160282927-7e733805-d474-4832-84f6-8fca1c77c6d4.png)

**Comment by MajorD4m4ge** [comment]
Odd.  I even put the requests through burp, the response comes back, but I
just get that "connection aborted".  Is there more details, or a deeper
debug option?

**Comment by stasinopoulos** [comment]
Nope, there is no deeper debug (i.e. `-v` option ranges: 1-4).
In my opinion, the simplest way in order to identify the problem, is to run commix and check requests in conjunction with burp (i.e. trial n' error :P )

**Comment by MajorD4m4ge** [comment]
Hmm. Ok. I did that. The connection was normal. Any idea where is code I can look to see what causes that error?

**Comment by stasinopoulos** [comment]
Take a look here: https://github.com/commixproject/commix/blob/6e138cdd9ed8f01c260afd5f1f56314010197cd4/src/core/requests/redirection.py#L208
