### ISSUE TITLE
Unhandled exception Error

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#759]
[critical] Unhandled exception occurred in '3.5-dev#34'. It is recommended to retry your run with the latest (dev) version from official GitHub repository at 'https://github.com/commixproject/commix.git'. If the exception persists, please open a new issue at 'https://github.com/commixproject/commix/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you.
Commix version: 3.5-dev#34
Python version: 3.9.11
Operating system: posix
Command line: commix.py --url=********************************** --batch

Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 806, in <module>
    if menu.options.MULTI_TARGETS:
AttributeError: 'Values' object has no attribute 'MULTI_TARGETS'
----------------------------------------------------------------------------------------------------------------------------------------

This is a new error i am getting today when i want to do a scan on a target i have the latest version of commix installed on my kali linux. What could be the problem could this be a kali linux issue and not a commix issue ?

**Comment by stasinopoulos** [comment]
This is a duplicate with https://github.com/commixproject/commix/issues/757. 
I will push a hot-fix (regarding that issue) within the next few days.

**Comment by stasinopoulos** [comment]
Fixed (update to dev#35)

**Comment by Anthonymcqueen21** [comment]
Okay thanks for the update didn't know this was a duplicate.
