### ISSUE TITLE
"Gibberish" ?

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#780]
![image](https://user-images.githubusercontent.com/23253941/188771758-c87806e2-e257-4f63-b776-834ed94f9592.png)

Why does commix show "Gibberish" when in os_shell would be a classic case of a false positive or just a wrong injection point ?

**Comment by stasinopoulos** [comment]
In that case (of a false positive) try to use `--ignore-session` or `--flush-session` and re-run.

**Comment by Anthonymcqueen21** [comment]
thanks i will give it a try and see if it works next test.

**Comment by Anthonymcqueen21** [comment]
Will you update Tampers ? Some of them are not supported or outdated.
