### ISSUE TITLE
Problem displaying results

### ISSUE THREAD

**Issue by bizibabe** [commixproject/commix#782]
Hello,

I have a problem displaying the result of a command in blind mode. 
The size of the result is correct but I only have backslashes :(
![image](https://user-images.githubusercontent.com/60073248/193474455-0a1cdd8a-4bab-44f4-a22b-07d802cbb102.png)

**Comment by stasinopoulos** [comment]
Hmm @bizibabe this behavior is quite strange. 

First of all, make sure that it's not false positive result (i.e. try to re-run using `--ignore-session`). 
In case you make sure it's vulnerable, try to use other enumeration option(s) from the list (i.e. `--sys-info`). 

**Hint:** Regarding time-related attacks, you can use the `--charset` option in order to set the injection charset (e.g. "0123456789abcdef")

**Comment by tbiziv** [comment]
No, it's not a false positive.
I just found the problem. I'm testing a local vulnerability that is a special case.
Your payload to return the ASCII value does not work with me:
`str=$(printf "%d" "'$char'")`
Using this payload `str=$(echo -n $char | od -An -tuC | xargs)` works :)

**Comment by bizibabe** [comment]
No, it's not a false positive.
I just found the problem. I'm testing a local vulnerability that is a special case.
Your payload to return the ASCII value does not work with me:
str=$(printf "%d" "'$char'")
Using this payload str=$(echo -n $char | od -An -tuC | xargs) works :)

**Comment by stasinopoulos** [comment]
Hello @bizibabe, I slightly changed the payload. Kindly update to "dev#7" and check again.

**Comment by bizibabe** [comment]
Hello @stasinopoulos 
Your are changed the payload `str=$(printf "%d" "'$char'")` to `str=$(printf '%d\n' "'$char'")` ?
Why not use my payload `str=$(echo -n $char | od -An -tuC | xargs)` ?
I have no result now :
![image](https://user-images.githubusercontent.com/60073248/194549860-117b46f2-2d38-4b01-b1f4-6ccf24190d7f.png)

**Comment by stasinopoulos** [comment]
The main reason why, is because every generated payload should consist of only one separator (e.g. only ";", "&&", "|" etc) and this separator should be used in case of commands chaining.

**Comment by stasinopoulos** [comment]
@bizibabe fyi added a new tamper script `printf2echo.py` that replaces the printf-based ASCII to Decimal `printf "%d" "'$char'"` with `echo -n $char | od -An -tuC | xargs`.

![Screenshot 2022-10-08 at 10 03 39 AM](https://user-images.githubusercontent.com/5289251/194694641-a6cd8eb5-473b-4b93-a520-4a27bc92f403.png)
