### ISSUE TITLE
Not converting integer datatype to string datatype while injecting payloads in JSON body

### ISSUE THREAD

**Issue by darshanpjpt** [commixproject/commix#788]
When the tool injects payloads in integer type parameter in JSON body, it does not add double quotes around the value.

For example, if there is JSON parameter `ID: 2`, the payload will be injected like `ID: 2PAYLOAD_HERE`. 
But that should be `ID: "2PAYLOAD_HERE"`.

### Suggested fix
Please add double quotes while injecting payloads into the integer type field.

## Sample request captured with --proxy
```
POST /search.php HTTP/1.1
Content-Length: 40
Host: example.com
User-Agent: commix/v3.6-dev#24 (https://commixproject.com)
Accept: */*
Content-Type: application/json
Accept-Encoding: gzip, deflate
Connection: close

{"Id":12345.print(phpinfo()),"lan":"en"}
```

**Comment by stasinopoulos** [comment]
Hello @darshanpjpt , why don't you put the double quotes in data like the following `{"Id":"12345","lan":"en"}` in order to inject the payload inside the double quotes?

**Comment by darshanpjpt** [comment]
Hello @stasinopoulos,

I can not provide double quotes in the input itself.

Because, as you stated - '123 is the number 123 and "123" is a string'.

So If I provide double quotes in the input itself, It will be sent as a string every time even if the payload is inserted in another field. 

For Example, Manually providing `{"Id":"12345","lan":"en"}` will be fine when the payload is getting injected in `Id` param, but may cause error when injecting payload in `lan` parameter.

Also this suggestion is already implemented by sqlmap. It converts to string while sending the payloads.

**Comment by stasinopoulos** [comment]
Since the parameter (i.e `Id`) accepts int value (i.e `12345`), I can't see the point of converting the payload to string by enclosing it into quotes (i.e `"12345"`).
