### ISSUE TITLE
Feature Request: Powershell Tricks

### ISSUE THREAD

**Issue by xsuperbug** [commixproject/commix#79]
add support for this tricks.

https://twitter.com/vysecurity/status/857734235695796225
https://twitter.com/vysecurity/status/859120856588582912

**Comment by stasinopoulos** [comment]
Added a new tamper script "caret.py" that adds the caret symbol (^) between the characters of the generated payloads. https://github.com/commixproject/commix/commit/09288393dd1029cc8d56bc4508b5330fe94b7afa
