### ISSUE TITLE
Set Language

### ISSUE THREAD

**Issue by Johnsavadkuhi** [commixproject/commix#790]
## What's the problem (or question)?
Hello everyone,

I could not find out how to set a language to test only it, for example for testing a ruby on rails based website, commix only should test command injection for ruby on rails but it tests all commands from all languages like as php, python and others.

Is there any solution ?

**Comment by stasinopoulos** [comment]
Command injection is an attack in which the goal is the execution of arbitrary commands on the host operating system (i.e Windows or Unix-based) via a vulnerable application and has nothing to do with the language that the application is written in [1][2].

[1] https://owasp.org/www-community/attacks/Command_Injection
[2] https://portswigger.net/web-security/os-command-injection
