### ISSUE TITLE
Commix didnt run after Testing connection to the target URL.

### ISSUE THREAD

**Issue by M-Tofla** [commixproject/commix#793]
HI,

i have a problem when using commix, t
his is my command : commix -u "https://test.test" --method="post" --data='{JSON_DATA}' --headers="auth  bearer" --all

the commix stop the target

![commix](https://user-images.githubusercontent.com/45419019/205000219-4b01237f-38b5-49c7-b528-cd7d3b12fc60.png)

Thank you

**Comment by stasinopoulos** [comment]
Hello @M-Tofla i suggest to parse the HTTP requests through HTTP proxy (i.e `--proxy` option) in order identify the root-cause regarding that issue.

**Comment by M-Tofla** [comment]
Hello @stasinopoulos 

its Invalid HTTP authentication type 'Bearer'
