### ISSUE TITLE
Temporary failure in name resolution.

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#799]
I have the latest version of commix updated and working well but whenever i use the -v1 option or similar i constantly get this issue with commix. I have updated and pinged a website and it worked and i updated the firewall and tcp settings on my end and commix continues to give me the error of "Temporary failure in name resolution". 

└──╼ $ sudo ufw allow 53/tcp
Rules updated
Rules updated (v6)
┌─[anthonyp@parrot]─[~]
└──╼ $sudo ufw reload
Firewall not enabled (skipping reload)
┌─[anthonyp@parrot]─[~]
└──╼ $sudo firewall-cmd --add-port=43/tcp --permanent
sudo: firewall-cmd: command not found
┌─[✗]─[anthonyp@parrot]─[~]
└──╼ $ sudo firewall-cmd --add-port=43/tcp --permanent
sudo: firewall-cmd: command not found
┌─[✗]─[anthonyp@parrot]─[~]
└──╼ $ sudo firewall-cmd --add-port=53/tcp --permanent
sudo: firewall-cmd: command not found
┌─[✗]─[anthonyp@parrot]─[~]
└──╼ $sudo firewall-cmd --reload
sudo: firewall-cmd: command not found
┌─[✗]─[anthonyp@parrot]─[~]
└──╼ $ ping phoenixnap.com
PING phoenixnap.com (172.67.14.186) 56(84) bytes of data.
64 bytes from 172.67.14.186 (172.67.14.186): icmp_seq=1 ttl=55 time=17.9 ms
64 bytes from 172.67.14.186 (172.67.14.186): icmp_seq=2 ttl=55 time=16.8 ms
64 bytes from 172.67.14.186 (172.67.14.186): icmp_seq=3 ttl=55 time=16.7 ms
^C
--- phoenixnap.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2001ms
rtt min/avg/max/mdev = 16.668/17.127/17.915/0.559 ms
┌─[anthonyp@parrot]─[~]
└──╼ $

Is there anything else i can do to fix this problem i am having ?

**Comment by stasinopoulos** [comment]
Similar with https://github.com/commixproject/commix/issues/792

**Comment by stasinopoulos** [comment]
@Anthonymcqueen21 i suggest to parse the HTTP requests through HTTP proxy (i.e --proxy option) in order identify the root-cause regarding that issue.

**Comment by Anthonymcqueen21** [comment]
Fine
