### ISSUE TITLE
Problem while doing authenticated scan

### ISSUE THREAD

**Issue by vojtapolasek** [commixproject/commix#80]
Hi,
I would like to use Commix to test for vulnerabilities in a web application which requires cookie-based authentication. Before trying this tool on our application, I tried WebGoat, because it is quite similar to our environment. I tried following:
1. Supplied appropriate cookie through --cookie="JSESSIONID=blahblah" and --referer=http://blahblah
2. I created a request file containing all needed parameters.
None of methods worked. I always received a 302 redirection to Login page.
I tried the same request file with Sqlmap, which can also read input from request files and it didn't receive any redirection and happyly started to search for vulnerabilities.
Could you please check this against WebGoat? I use WebGoat 6.0.1. It can be downloaded as a Docker image.
I use commix cloned from master branch of your repo. I am running Arch Linux. I attach the request file.
Thank you.
[commix_input.txt](https://github.com/commixproject/commix/files/1000507/commix_input.txt)

**Comment by stasinopoulos** [comment]
Hello @vojtapolasek , have you tried to ignore the redirection message?
```
[!] Warning: Got a 302 redirection (http://192.168.xxx.xxx/xxx/DVWA/login.php).
[?] Do you want to follow the identified redirection? [Y/n] > n
[*] Identifying the target server... [ SUCCEED ]
```

**Comment by vojtapolasek** [comment]
Yes, I did this. I attach the traffic file. As you can see, WebGoat returns me to the main page of the application. Have you tried this on real Webgoat installation?
I used
commix -r <requestfile> --level=3 -t <traffic_file>
Before I ran this I logged into the application and replaced cookie in the request file with valid one.
[commix_output.txt.gz](https://github.com/commixproject/commix/files/1003670/commix_output.txt.gz)

**Comment by stasinopoulos** [comment]
I know that in DVWA the authenticated scan redirects you to the login page (i am planning to fix that bug) but if you don't want to follow the 302 redirection it works fine with the authenticated page. 
```
[!] Warning: Got a 302 redirection (http://192.168.xxx.xxx/xxx/DVWA/login.php).
[?] Do you want to follow the identified redirection? [Y/n] > n
[*] Identifying the target server... [ SUCCEED ]
```

Could you please check if that behavior still exists against DVWA, using exactly the same options as WebGoat?

**Comment by vojtapolasek** [comment]
Yes, I can confirm that it finds the vulnerability in DVWA if I decline to follow the redirection. So do you think that the problem is in Webgoat and not in Commix?
