### ISSUE TITLE
Time delays.

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#808]
**Unexpected time delays have been identified due to unstable requests. This behavior may lead to false positive results. How do you want to proceed? [(C)ontinue/(s)kip/(q)uit] > q**
---------------------------------------------------------------------------------------------------------------------
It seems no matter which parameter i test or technique i use, this issue keeps popping up and i wonder if i am using this tool wrong the whole time. Or maybe the simple fact is the parameter is protected no matter which tamper script i use to test, this leads to the same issue which leads to false positives and wasted effort. Your tool works fine, and it's updated, but if you can tell me, what is the issue here ?

- Am i using Commix incorrectly ?
- Simply a false positive and i should move on ?

**Comment by stasinopoulos** [comment]
Probably is a false positive.

**Comment by Anthonymcqueen21** [comment]
Alright thank you as usual.
