### ISSUE TITLE
Commix sends requests with GET method even if POST method is used (injection levels 2,3)

### ISSUE THREAD

**Issue by vojtapolasek** [commixproject/commix#81]
The title says it all. I discovered this while trying to get results for bug with authenticated scan. In my request file, I use POSt HTTP method. But looking into the generated traffic file, I can see that Commix uses GET method except for the first request where it uses POSt method correctly.
Running latest Commix from master.

**Comment by stasinopoulos** [comment]
Sorry but i can't confirm that. Please provide me with more information, if it is possible.

I used the following command:
`$ python commix.py -r '/xxxx/xxxx/xxxx/req.txt' -v2 --proxy="127.0.0.1:8080"`

**Commix (verbose level = 2)**
![screenshot from 2017-05-18 18-53-19](https://cloud.githubusercontent.com/assets/5289251/26211574/6c768568-3bfb-11e7-8ce9-02502e8074ce.png)

**Burp HTTP traffic**
![screenshot from 2017-05-18 18-56-40](https://cloud.githubusercontent.com/assets/5289251/26211736/e82c738e-3bfb-11e7-83fb-78e7a7649028.png)

**Comment by stasinopoulos** [comment]
I saw what you mean with that issue. The problem that you are describing exists in injection levels 2,3 (i.e command injections over Cookies, User-agent, Referer, etc).
