### ISSUE TITLE
2 years Zero command injections

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#819]
First off, I love your tool, I will continue to use it because command injections are the only bug class I care about and i am learning more about. But with that said, I have yet to find a valid command injection flaw on any of my target applications when I hunt. So in the end no matter what parameter, technique, tamper I use I can't find a command injection bug. I look at your white papers and use your commx-testbed for training, the tool works fine. But when it comes to live hunting, the common errors I get when I hunt on a live site. All the tutorials out there available make it look way too easy, when in reality it's not.

- Unexpected time delays
-  404, 405 errors
- Redirects
- Cookie issues
- Etc...

Look this is no one's fault but my own I am trying to master this tool and trying to figure it out and the closest I got was a false positive. You don't have a discussion section, so ethical hackers like myself can discussion issues and help each other to figure it out. I know for a fact this bug is not extinct, or else you would not have to update this tool every couple of months. If there is any helpful advice, i would greatly appreciate it. The tutorials out there are a little outdated and do not show the full capabilities of this tool. I am sure i am not the only one who is struggling to find command injection out there and loves this tool compared to the countless others out there. 

**At this point i should have found a valid OS command injection vulnerability, is it simply i am not using this tool correctly or something else I don't know.**

- Thank you

**Comment by stasinopoulos** [comment]
Keep reading, keep learning.

**Comment by Anthonymcqueen21** [comment]
Thank you i will.
