### ISSUE TITLE
shocker-cgi_list.txt is not found

### ISSUE THREAD

**Issue by crypticsilence** [commixproject/commix#825]
Maybe its something simple I'm missing? Apologies if this is me being braindead.. 

## What's the problem (or question)?
[08:41:41] [critical] The pages / scripts list (/usr/local/lib/python3.9/dist-packages/commix-3.8.dev0-py3.9.egg/src/txt/shocker-cgi_list.txt) is not found
Can't seem to find this file.  [..]/txt does not exist.
└──╼ $find /usr/local/lib/python3.9/dist-packages/ | grep -i shocker
[no output]
Found it here:
└──╼ $sudo find /usr | grep -i shocker
/usr/share/commix/src/txt/shocker-cgi_list.txt
Then removed with sudo commix --install [y to remove]
and reinstalled with sudo commix --install [it reinstalls]
Same issue.. can't find shocker-cgi_list.txt. Now it still errors out with the same file, and the file is gone from /usr:
└──╼ $sudo find /usr | grep -i shocker
[no output]
## How can we reproduce the issue?
sudo commix --update

## What are the running context details?
* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`): git clone or pip3 install (can't remember?)
* Client OS (e.g. `Linux (Ubuntu)`) : Parrot Sec OS 5.0
* Program version (`python commix.py --version` or `commix --version` depending on installation):  v3.8-dev#1
* Target OS (e.g. `Linux (Debian)`):  Linux 5.18.0
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`): -
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works): -
* Relevant console output (if any):
└──╼ $commix -u http://searcher.htb
[...]
[08:41:41] [info] Testing connection to the target URL. 
[08:41:41] [critical] The pages / scripts list (/usr/local/lib/python3.9/dist-packages/commix-3.8.dev0-py3.9.egg/src/txt/shocker-cgi_list.txt) is not found
└──╼ $ ls /usr/local/lib/python3.9/dist-packages/commix-3.8.dev0-py3.9.egg/src/txt
ls: cannot access '/usr/local/lib/python3.9/dist-packages/commix-3.8.dev0-py3.9.egg/src/txt': No such file or directory

└──╼ $ls /usr/local/lib/python3.9/dist-packages/commix-3.8.dev0-py3.9.egg/
EGG-INFO  src

* Exception traceback (if any):

**Comment by stasinopoulos** [comment]
Try to download commix by cloning the official Git repository:
`git clone https://github.com/commixproject/commix.git commix`

Regarding the reported issue, you may have to contact with your Linux distro maintenance / dev team.
