### ISSUE TITLE
displaying interactive shell in batch mode

### ISSUE THREAD

**Issue by vojtapolasek** [commixproject/commix#83]
Hi,
I need to run Commix in a noninteractive script. I used the --batch option but after finding a vulnerability, Commix drops me into its pseudoshell. Could this be changed for --batch switch?
Thanks alot.

**Comment by stasinopoulos** [comment]
Hello, 

The "--batch" switch can be used in order to run commix as a batch tool (without any user's interaction when commix requires it). FYI, this switch is forcing commix to operate with a default behaviour whenever user's input would be required. Currently there no way to avoid the pseudoshell.
