### ISSUE TITLE
Suggestion: Adding the -r request.txt like in sqlmap 

### ISSUE THREAD

**Issue by UncleJ4ck** [commixproject/commix#831]
I have a suggestion of adding the request argument like in sqlmap ? -r to read each parameter and try all the command injections payloads in it, it will make it easier to read the cookies and each necessary parameter

**Comment by stasinopoulos** [comment]
hello @UncleJ4ck, commix supports the `-r` flag for loading HTTP request from a file.

**Comment by UncleJ4ck** [comment]
my bad didn't read well the doc ! thanks
