### ISSUE TITLE
403 bypass

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#841]
After using your tool for 2 years i have not found a command injection vulnerability, one of the biggest problems is the infamous 403 error. I am trying to figure out which tamper i can use to bypass this and no luck. Is there any advice to help me solve this ongoing issue, if not that's fine, just a frustrating process in the ongoing hunt. I don't expect a hand out, just a little advice as i continue forward with command injection.

- thank you.

**Comment by stasinopoulos** [comment]
Sorry @Anthonymcqueen21 but i can't help you on that, since bypassing of any protection mechanism(s) is entirely user's job.

**Comment by Anthonymcqueen21** [comment]
Thats fine just a frustrating process.
