### ISSUE TITLE
No Prompt to Skip Blind Checks When the Parameter if Found Vulnerable With "classic command injection technique"

### ISSUE THREAD

**Issue by darshanpjpt** [commixproject/commix#845]
## What's the problem (or question)?
When a parameter is found to be vulnerable, it doesn't ask to skip the blind command injection checks. It asks if we want to skip code injection checks, but the blind command injection checks are executed by default.
![Screenshot](https://github.com/commixproject/commix/assets/71147956/63801a4e-2284-40dd-aa30-9d05c096a2da)

## Idea for a solution
It is good to have a prompt to skip all the other checks including the blind checks when a parameter is found vulnerable.

**Comment by stasinopoulos** [comment]
Hello @darshanpjpt fyi, in order to achieve what you mention, you can simply use the `--technique` option (to specify injection technique(s)) or the `--skip-technique` option (to specify injection technique(s) to skip).

**Comment by darshanpjpt** [comment]
Hey @stasinopoulos 

I can not use that option, since it will skip the blind check every time. 

It should be conditional,
If normal command injection found -> skip checks for blind
If normal command injection not found -> check for blind

**Comment by stasinopoulos** [comment]
Done https://github.com/commixproject/commix/commit/6cca54e500be0a3435177117669dc6b9d2a6614a
