### ISSUE TITLE
Why is it so hard ?

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#847]
I mean, I have been using your tool for a couple of years now and no matter how hard I try I always get the same old errors:

- Unexpected time delays
- 404 errors
- 429 errors
- Not injectable
- Etc.

---------------------------------------------------------------------------------------------------------
This tool to me is amazing but why is it so hard to find a command injection flaw, I study and follow the tutorials to the book. I also learn more and more about OS command injection each and every day, i am not lazy. There has to be something i am doing wrong like i said before this tool is claimed to be **"Easy"** when it comes to find OS command injection, but that is not true in the real world at least for me it's frustrating. I dont blame you i just wish i can find ONE command injection flaw i can't figure out what i am doing wrong. 

**I try to find parameters that are uncommon and i still get the same old issues i also use weevely to create a backdoor, but that only works in the command injection test bed.**

Please, any advice, don't ignore your tool is what i am trying to master.

**Comment by stasinopoulos** [comment]
Similar with https://github.com/commixproject/commix/issues/819
