### ISSUE TITLE
Doesn't read cookie from file

### ISSUE THREAD

**Issue by Themercee** [commixproject/commix#85]
When using -r filename, I was expecting commix to read the Cookie and header from the file and use it in future requests, as sqlmap. Is it normal it did't use it?

**Comment by stasinopoulos** [comment]
Hello, what version of commix do you use?

**Comment by Themercee** [comment]
v2.0-dev#22

**Comment by stasinopoulos** [comment]
Hey, could you please provide me more information about this bug?

**Comment by stasinopoulos** [comment]
I think it's fine.
![screenshot from 2017-06-14 12-03-24](https://user-images.githubusercontent.com/5289251/27124440-cad68c94-50f9-11e7-9786-bc29e8886138.png)
