### ISSUE TITLE
Download on Windows alternative ?

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#850]
How do you download Commix on Windows example using Command Prompt or Windows PowerShell, some of the command are way different from Linux. I can't clone the latest repository, and I can't download the latest zip file or tarball files without setting off my firewall on my main system. 

Any ideas why because Kali-Linux and Parrot OS are so slow when I use your tool I am looking for other alternatives.

**Comment by stasinopoulos** [comment]
Sorry i cant help on that.

**Comment by Anthonymcqueen21** [comment]
Why are you always a prick no matter the question, you simply ignore I am not a troll, I am a person who is asking questions that Google can't answer. I have noticed this with other people who ask questions as well.

**Comment by stasinopoulos** [comment]
If you ain't like my way, just find another tool to use.

**Comment by Anthonymcqueen21** [comment]
Your such an asshole, pure and simple, that made an incompetent tool.

**Comment by stasinopoulos** [comment]
Well, no matter what you say and / or curse, my previous answer still stands. 🤷‍♂️ 
BTW a friendly tip - for the next tool you're going to involve with - keep in mind to spend (at least) couple of hours educating before going into discussion(s) (i.e. https://github.com/commixproject/commix/issues?page=1&q=is%3Aissue+author%3AAnthonymcqueen21) why something ain't work.
