### ISSUE TITLE
Tor HTTPS proxy does not change IP (privoxy?)

### ISSUE THREAD

**Issue by C-Bouthoorn** [commixproject/commix#86]
Using `--tor` on an HTTPS address does not seem to change the IP.

```
# ./commix.py --tor -u "http://example.net" -v4
[...]
[*] Testing privoxy proxy settings 127.0.0.1:8118... [ SUCCEED ]
[+] Your ip address appears to be xxx.xxx.xxx.xxx (Tor IP)
```

```
# ./commix.py --tor -u "https://example.net" -v4
[...]
[*] Testing privoxy proxy settings 127.0.0.1:8118... [ SUCCEED ]
[+] Your ip address appears to be yyy.yyy.yyy.yyy (my own IP)
```

```
# grep -Ev "^(#|$)" /etc/privoxy/config
[...]
listen-address  127.0.0.1:8118
[...]
forward-socks5 / localhost:9050 .
```

Last line as per https://github.com/commixproject/commix/issues/59 to fix the `Tor is not an HTTP proxy` error.

```
# set | grep proxy
all_proxy=socks://localhost:9050/
http_proxy=http://localhost:8118/
no_proxy=localhost,127.0.0.0/8,::1
```

After reading https://www.privoxy.org/user-manual/quickstart.html: "Set your browser to use Privoxy as HTTP and HTTPS (SSL) proxy by setting the proxy configuration for address of `127.0.0.1` and port `8118`", I tried `export https_proxy="$http_proxy"` but that didn't change the outcome

```
# grep -Ev "^(#|$)" /etc/tor/torrc
# grep -Ev "^(#|$)" /etc/tor/torsocks.conf 
TorAddress 127.0.0.1
TorPort 9050
```

I am running the latest Kali in a Virtualbox, but this also happens outside of Virtualbox, so that doesn't seem relevant to me.

Happens on commix `1.9-stable` and `2.0-dev#22` with tor `0.2.9.10` and `0.3.0.7` and privoxy `3.0.26`

**Comment by stasinopoulos** [comment]
Thanks for the bug report, i ll check it out soon.
