### ISSUE TITLE
Feature Request: Skip "os_shell" option.

### ISSUE THREAD

**Issue by narasimhareddy5x5** [commixproject/commix#868]
While using the "--batch" option, after finding that the parameter is vulnerable, Commix prompts the "os_shell". This feature works well when testing one or two URLs; we can simply enter "back" to return to the test second URL (or second parameter). However, when testing hundreds of URLs, every time Commix finds a vulnerable parameter, it prompts the "os_shell." Without closing the OS shell, we can't test the next URL.

All I need is to provide the "--skip-os-shell" option when using the "--batch" option,

like this:
$ python3 commix.py -m urls.txt --batch --skip-os-shell

This way, we can easily test hundreds of URLs while we are sleeping.

**Comment by stasinopoulos** [comment]
Try to set predefined answer(s) (i.e. via `--answers` option) during your scan.

```
python3 commix.py -u "http://target/test.php?param=1" --answers="shell=n, skip=n" --batch

[...snip...]
[18:01:53] [info] Heuristic (basic) tests shows that GET parameter 'param' might be injectable (possible OS: 'Windows').
[18:02:04] [info] Testing the (results-based) classic command injection technique.
[18:02:04] [info] GET parameter 'param' appears to be injectable via (results-based) classic command injection technique.
           |_ 1%26for /f "tokens=*" %i in ('cmd /c "set /a (9+21)"') do @set /p = WZTTSR%iWZTTSRWZTTSR
GET parameter 'param' is vulnerable. Do you want to prompt for a pseudo-terminal shell? [Y/n] > n
Do you want to continue with testing the classic command injection technique? [y/N] > N
Skipping of further command injection tests is recommended. Do you agree? [Y/n] > n
[...snip...]
```

**Comment by narasimhareddy5x5** [comment]
thanks :)
