### ISSUE TITLE
No such file or directory: '~/.commix/output'

### ISSUE THREAD

**Issue by Maza030** [commixproject/commix#869]
wheni use the basic command, i got this error 
13:25:20] [info] Testing connection to the target URL.  
[13:25:20] [warning] Potential CAPTCHA protection mechanism detected.
[13:25:20] **[critical] No such file or directory: '~/.commix/o**utput'.
which i can understand can be solved with this command 
mkdir ~/.commix/output
even when i gave the folder all permission still the same error

**Comment by stasinopoulos** [comment]
Hey, provide me with more information about this issue (i.e the version of Commix, OS and the Python version.)
