### ISSUE TITLE
INJECT_TAG not cleared in body parameter string when skipping anti-CSRF Token

### ISSUE THREAD

**Issue by xerxoria** [commixproject/commix#870]
I run into the the following issue with b7b9a2f9afd2029403ab97972221c52f226055c3 while using an request exported from burp:

When commix detects and skips an anti-CSRF Token at position _n_ in the body parameter string it does not clear the prior set `settings.INJECT_TAG` on parameter _n-1_. From that point on the parameter at _n-1_ is tested for each remaining parameter _n+m_ as `settings.INJECT_TAG` exists two times in the parameter string, e.g:

having `p1=a&p2=b&p3=<anti-csrf>&p4=c&p5=d` will test p1,p2,p2,p2 because also it is set at p4 and p5 in the following iterations, the `INJECT_TAG` at p2 is never cleared.

I fixed the issue f_or my specific case_ by patching `parameters.py`:

```bash
kali@kali:~/src/commix$ git diff master
diff --git a/src/core/requests/parameters.py b/src/core/requests/parameters.py
index f38d91dd..fe45bb96 100755
--- a/src/core/requests/parameters.py
+++ b/src/core/requests/parameters.py
@@ -322,6 +322,7 @@ def do_POST_check(parameter, http_request_method):
           value = checks.value_boundaries(all_params[param], value, http_request_method)
         # Ignoring the anti-CSRF parameter(s).
         if checks.ignore_anticsrf_parameter(all_params[param]):
+          all_params[param - 1] = ''.join(all_params[param - 1]).replace(settings.INJECT_TAG, "")
           continue
         # Replace the value of parameter with INJECT_HERE tag
         if len(value) == 0:
```

**Comment by stasinopoulos** [comment]
Done https://github.com/commixproject/commix/commit/f14a1fab873f3a0bf862318b016258c824c5e465
