### ISSUE TITLE
can't start it in windows 10

### ISSUE THREAD

**Issue by Cyber-Clash** [commixproject/commix#871]
## What's the problem (or question)?

Can't start yout tool, atm.

## Do you have an idea for a solution?

Not really...

## How can we reproduce the issue?

____________________________________________________________________________________________________
This is the error when i try to start it:

C:\Users\windows01>commix
Traceback (most recent call last):
  File "C:\_tools\commix\commix.py", line 18, in <module>
    __import__("src.utils.version")
  File "C:\_tools\commix\src\utils\version.py", line 17, in <module>
    from src.utils import settings
  File "C:\_tools\commix\src\utils\settings.py", line 25, in <module>
    from src.thirdparty.six.moves import urllib as _urllib
ModuleNotFoundError: No module named 'src.thirdparty.six.moves'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\_tools\commix\commix.py", line 25, in <module>
    print(settings.print_critical_msg(err_msg))
          ^^^^^^^^
NameError: name 'settings' is not defined
____________________________________________________________________________________________________

## What are the running context details?

* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (e.g. `Linux (Ubuntu)`)
* Program version (`python commix.py --version` or `commix --version` depending on installation): 
* Target OS (e.g. `Linux (Debian)`): 
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`):
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works):
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by stasinopoulos** [comment]
Hey @Cyber-Clash sorry, but I am not able to reproduce the issue.
On the following screenshot, i run commix (latest dev#19 version) on a **Win10** w/ Python version **3.11.6**:

![Screenshot 2023-11-19 at 09 36 16](https://github.com/commixproject/commix/assets/5289251/9d233d37-381f-4fe0-bfc8-d20817f6b29f)

Note: If the issue persists on your side, I would suggest to run commix on Linux VM (i.e. Kali Linux etc)
