### ISSUE TITLE
NameError: name 'settings' is not defined & ModuleNotFoundError: No module named 'src.thirdparty.six.moves'

### ISSUE THREAD

**Issue by Abhishek-Dirisipo** [commixproject/commix#885]
## What's the problem (or question)?

when i try to run commix, this error occurs:

Traceback (most recent call last):
  File "/Users/abhishek/BB/tools/commix/commix.py", line 18, in <module>
    __import__("src.utils.version")
  File "/Users/abhishek/BB/tools/commix/src/utils/version.py", line 17, in <module>
    from src.utils import settings
  File "/Users/abhishek/BB/tools/commix/src/utils/settings.py", line 26, in <module>
    from src.thirdparty.six.moves import urllib as _urllib
ModuleNotFoundError: No module named 'src.thirdparty.six.moves'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/abhishek/BB/tools/commix/commix.py", line 25, in <module>
    print(settings.print_critical_msg(err_msg))
          ^^^^^^^^
NameError: name 'settings' is not defined

## Do you have an idea for a solution?

no

## How can we reproduce the issue?

1. use mac with latest python 3.12.1
2. try to run commix.py with python3
3. the error will occur

## What are the running context details?

* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`): git clone 
* Client OS (e.g. `Linux (Ubuntu)`):  mac os
* Program version (`python commix.py --version` or `commix --version` depending on installation): python 3.12.1

* Relevant console output (if any): 

Traceback (most recent call last):
  File "/Users/abhishek/BB/tools/commix/commix.py", line 18, in <module>
    __import__("src.utils.version")
  File "/Users/abhishek/BB/tools/commix/src/utils/version.py", line 17, in <module>
    from src.utils import settings
  File "/Users/abhishek/BB/tools/commix/src/utils/settings.py", line 26, in <module>
    from src.thirdparty.six.moves import urllib as _urllib
ModuleNotFoundError: No module named 'src.thirdparty.six.moves'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/abhishek/BB/tools/commix/commix.py", line 25, in <module>
    print(settings.print_critical_msg(err_msg))
          ^^^^^^^^
NameError: name 'settings' is not defined

**Comment by stasinopoulos** [comment]
Hey, @Abhishek-Dirisipo sorry, but I am not able to reproduce the reported issue. 
Try to update commix to the latest (dev) version and/or use different version of Python and check again.

**Comment by Abhishek-Dirisipo** [comment]
i re-installed python3.12.1(latest) and re-cloned the latest commix . it still shows me the same error.

**Comment by stasinopoulos** [comment]
This is some kind of environment issue (that i am not able to reproduce) similar with  https://github.com/commixproject/commix/issues/875.
I would suggest to run commix on Linux VM (i.e. Kali Linux etc)

**Comment by Abhishek-Dirisipo** [comment]
so , it is an issue with mac i think.

**Comment by stasinopoulos** [comment]
FYI, i just run commix (v3.9-dev#43) on my OSX w/ Python version 3.9.14.
![Untitled](https://github.com/commixproject/commix/assets/5289251/c11459bd-209e-4874-b822-3e378d814e5c)

**Comment by dkmcgrath** [comment]
This seems to be a problem when the six library is already installed. Changing the imports via

`find $COMMIX_ROOT -iname "*.py" -exec sed -i '' 's/from src.thirdparty.six.moves import/from six.moves import/g' {} \;`

fixed this issue for me.

**Comment by Abhishek-Dirisipo** [comment]
3.9 it is working for the latest python version it is not working

**Comment by stasinopoulos** [comment]
![Untitled](https://github.com/commixproject/commix/assets/5289251/fc55e5bb-99a8-4b43-9dd3-4a349fd0db54)

**Comment by Abhishek-Dirisipo** [comment]
Thank you , now it is perfectly working fine
