### ISSUE TITLE
Error: The 'base64encode.py' tamper script does not exist

### ISSUE THREAD

**Issue by hack0mate** [commixproject/commix#90]
When I use tamper=tamper.py it most of runtimes gives back this Error 

[x] Error: The 'base64encode.py' tamper script does not exist.

Sometimes it passed without issue, but mostly with error.

I use linux 64

Could you recommended me something, please?

**Comment by stasinopoulos** [comment]
Hello @hack0mate and thanks for the issue. Could you please provide me with the screenshot of the command(s) that you have entered as well as the error output?

**Comment by hack0mate** [comment]
Hello,
 
 You can simply run with this command to check'up by yourself, please:
 
 python commix.py --url="http://**********************" --tamper=base64encode.py --random-agent --ignore-redirects --os="unix" --all --skip-waf

**Comment by stasinopoulos** [comment]
Wrong syntax. 
Use `python commix.py --url="http://**********************" --tamper=base64encode --random-agent --ignore-redirects --os="unix" --all --skip-waf`
