### ISSUE TITLE
tamper script does not exist (second order)

### ISSUE THREAD

**Issue by hack0mate** [commixproject/commix#91]
Sorry me for the continue but with syntax it was ok. 

I made wrong for copy/paste last time. Really sorry for than.

You can see a screenshot now, please.

Maybe you will give me a advice.

Thank's anyway for your eagle eye.
![commix_error](https://user-images.githubusercontent.com/11214358/27986898-f773fee8-6405-11e7-9b08-81c88cc95d69.jpg)

**Comment by stasinopoulos** [comment]
As i mentioned you in https://github.com/commixproject/commix/issues/90, your syntax is wrong. 
Remove the ".py" extension from "--tamper" option (i.e. `--tamper=base64encode`)
