### ISSUE TITLE
Commix exists after entering reverse_tcp

### ISSUE THREAD

**Issue by Aholicknight** [commixproject/commix#918]
## What's the problem (or question)?

I am having a problem where commix is quitting after entering reverse_tcp. I do not know why this is happening. To provide better help, I included a video of what's happening.
## Do you have an idea for a solution?

No. If I did, I wouldn't make this issue ticket.
## How can we reproduce the issue?

1. Get an OS shell
2. Once connected, type `reverse_tcp`
3. Then type `lhost (local IP here)`
4. Commix will exit

## What are the running context details?

* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`): apt-get
* Client OS (e.g. `Linux (Ubuntu)`): Kali Linux
* Program version (`python commix.py --version` or `commix --version` depending on installation):  v3.9 stable
* Target OS (e.g. `Linux (Debian)`): Linux (Don't know what kind, HTB does not say)
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`): Classic
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works): 
* Relevant console output (if any):
* Exception traceback (if any):

https://github.com/commixproject/commix/assets/7843719/46ad787c-8238-4de7-a0b3-29237a1fd623

**Comment by stasinopoulos** [comment]
@Aholicknight I am not able to reproduce the reported issue.
![Untitled](https://github.com/commixproject/commix/assets/5289251/25f4e0ce-4532-4080-abd7-e4cfcaf204ea)
Try to update commix to dev version (using git clone) that is under development / code refactoring.

**Comment by Aholicknight** [comment]
@stasinopoulos I am also having another problem when using a request exported with burp suite:


https://github.com/commixproject/commix/assets/7843719/9c1057fd-2862-47ee-99a5-ef3c7b8243c8

This file does exist.

**Comment by stasinopoulos** [comment]
@stasinopoulos as in the previous comment, try to update commix to dev version (using git clone) that is under development / code refactoring.

**Comment by stasinopoulos** [comment]
@Aholicknight  (as in the previous comment) try to update commix to dev version using git clone and check again.

**Comment by Aholicknight** [comment]
> @Aholicknight (as in the previous comment) try to update commix to dev version using git clone and check again.

@stasinopoulos I will do this now.
