### ISSUE TITLE
Crawler don't work

### ISSUE THREAD

**Issue by e2002e** [commixproject/commix#921]
Hi, I'm trying to use the option crawl:
--crawl 2
but it yields:
[warning] No usable links found (with GET parameters).

**Comment by stasinopoulos** [comment]
Hello @e2002e and thank you for your bug report. 
The issue you mention will be fixed in version v4.0-stable.
I will let you know when fix will be available in the master branch.

**Comment by e2002e** [comment]
@stasinopoulos the crawler is in fact working, providing we specify the protocol for the url parameter.

**Comment by e2002e** [comment]
Could it be possible to have a --forms option like in sqlmap ? Like this when we do a crawl it could take the POST formulars into account.
Or maybe there's a way to do so that I didn't find out ?
In a case of a website with a lot of possible interactions via POST, when crawling it's testing only get for each php page.
