### ISSUE TITLE
Commix Not Executed Properly When Run Programatically

### ISSUE THREAD

**Issue by nik-ngp** [commixproject/commix#923]
## What's the problem (or question)?
Commix has issues when running under an emulated terminal.

For example, I tried running it within Python (which does execution differently, it creates an actual process) and it worked (**edit it does not**):
`import subprocess`
`cmd = "commix -r req.txt --ignore-stdin --batch"`
`returned_value = subprocess.call(cmd, shell=True)`
`print(returned_value)`

## How can we reproduce the issue?
https://github.com/nik-ngp/commix-bug

When I run the program in the repo I receive this in the console:
![image](https://github.com/commixproject/commix/assets/78493781/84cda0aa-b177-4293-8346-44ed2790b409)

## What are the running context details?
* Installation method pacman
* Client OS Arch Linux, Garuda, x86_64
* Program version v4.0-dev#53

**Comment by stasinopoulos** [comment]
@nik-ngp honestly I don’t get the reason why to do that. Anyway, by knowing that in a Python environment works as it should, i am closing this down.

**Comment by nik-ngp** [comment]
> by knowing that in a Python environment works as it should, i am closing this down

The Python code actually doesn't work. My Python skills are a bit rusty and I have provided wrong code. 

The code I provided does not return output of the executed command, the file descriptors were inherited from the running process which meant that the executed command was writing directly to standard out & err. Instead of to a variable.

Here is an updated script:
`import subprocess`
`cmd = "commix -r req.txt --ignore-stdin --batch"`
`# cmd = "echo 123" # <--- Works`
`def do(command: str) -> str:`
`  try:`
`    return subprocess.check_output(`
`      command,`
`      shell = True`
`    ).decode('utf-8')`
`  except Exception as e:`
`    print(e)`
`    return 'Error'`
`output = do(cmd)`
`print(output)`

This code reproduces the same behavior I am experiencing in the Golang example. 

> honestly I don’t get the reason why to do that
I have a crawler that records requests with data and automatically targets them with Commix. Why would I have to crawl and run against endpoints when my script can? I am simply saving my own time.

**Comment by stasinopoulos** [comment]
@nik-ngp why not parsing targets (as a piped-in input) directly from your / other pentesting tools? 
(e.g https://x.com/commixproject/status/1525726750285733889)

**Comment by nik-ngp** [comment]
@stasinopoulos I did some attempts, however, it seems that it does not support piping in a raw requests.

**Comment by stasinopoulos** [comment]
I updated your code and now works fine.

```
import subprocess

url = "http://php.testsparker.com/nslookup.php?param=1"
cmd = f"commix -u {url} --batch --os-cmd=whoami --answers=\"shell=n\""

def do(command: str) -> str:
  try:
    return subprocess.run(
      command,
      shell = True
    )
  except Exception as e:
    print(e)
    return 'Error'
output = do(cmd)
print(output)
```

![image](https://github.com/commixproject/commix/assets/5289251/75f885cf-66ec-44c1-8cf3-dab7a68fb152)

**Comment by nik-ngp** [comment]
Hello @stasinopoulos.
I have to admit, you got me a bit confused. I'm unsure of what the updated code is meant to represent since it deviates from the purpose of my script in two ways:

- It does not rely to raw request as an input.
- It does not actually write anything into a variable. The output that's displayed in the screenshot is because the file descriptors of the process point to the terminal itself, not to an in-memory buffer. This is provable by commenting out the call to the `print` function which would still output Commix to the terminal.

**Comment by stasinopoulos** [comment]
@nik-ngp just of curiosity, have you tried the same using other (similar) tools (e.g. sqlmap etc)?

**Comment by nik-ngp** [comment]
@stasinopoulos Indeed I am using Sqlmap to tests against raw requests. It works nicely with my code.

**Comment by stasinopoulos** [comment]
Potential fix: https://github.com/commixproject/commix/commit/ebe84fac8a3f06db3590fd447434627d5ffef16e. Please check again.
