### ISSUE TITLE
Commix Not Executed Properly When Run Programatically

### ISSUE THREAD

**Issue by nik-ngp** [commixproject/commix#927]
## What's the problem (or question)?
Commix has issues when running under an emulated terminal.

I tried executing Commix via Python and it produces broken results. The program exits with status zero with no indication of issues.

Here is the code I used:
`import subprocess`
`cmd = "commix -r req.txt --ignore-stdin --batch"`
`# cmd = "echo 123" # <--- Works`
`def do(command: str) -> str:`
`  try:`
`    return subprocess.check_output(`
`      command,`
`      shell = True`
`    ).decode('utf-8')`
`  except Exception as e:`
`    print(e)`
`    return 'Error'`
`output = do(cmd)`
`print(output)`
## How can we reproduce the issue?
The same issue reproduced in Golang instead of Python (displaying that it is Commix specific issue, rather than Python) https://github.com/nik-ngp/commix-bug

When I run the program in the repo I receive this in the console:
![image](https://github.com/commixproject/commix/assets/78493781/84cda0aa-b177-4293-8346-44ed2790b409)

The code works if the output of the Commix is not trying to be read. This indicates that if a program inherits the file descriptors of a terminal it would work fine, however, if the file descriptors point to a buffer/s in memory it will break.

## What are the running context details?
* Installation method pacman
* Python version 3.12.3
* Client OS Arch Linux, Garuda, x86_64
* Program version v4.0-dev#53

**Comment by stasinopoulos** [comment]
Similar with https://github.com/commixproject/commix/issues/923
