### ISSUE TITLE
asking for help

### ISSUE THREAD

**Issue by hack0mate** [commixproject/commix#93]
I found that if I run command like this

`--url="http://************************" --tamper=base64encode --random-agent --proxy="10.192.154.30:8080" --ignore-redirects --os="unix" --all --skip-waf`

It gives me error:

`Unable to connect proxy`

I also tried without success

`--proxy=10.192.154.30:8080`

How I need run with --proxy=, please?

**Comment by stasinopoulos** [comment]
Sorry but i can't confirm that. Check your HTTP proxy (i.e. burp) and try again.

**Comment by hack0mate** [comment]
I'm really sorry, but I'm already checked with two OS and always same. If I run like this:
 
`--url="http://************************" --tamper=base64encode --random-agent --proxy="127.0.0.1:8080" --ignore-redirects --os="unix" --all --skip-waf`

It still gives me error:

`Unable to connect proxy`

And it not comes to burp.

But, if I run like this:

`--url="http://************************" --tamper=base64encode.py --random-agent --proxy="127.0.0.1:8080" --ignore-redirects --os="unix" --all --skip-waf`

It gives me error:

`[x] Error: The 'base64encode.py' tamper script does not exist.`

But, MAGIC, I have no error `Unable to connect proxy` It comes via proxy properly, like a charm. That's why I'm asked you to add solution to run tamper with it whole filename .py

But, you said it's ok.

Ok, for now, via burp proxy works without tamper or tamper works without proxy.

Anyone can confirm that, please?

**Comment by stasinopoulos** [comment]
Sorry but i can't help you. 
![screenshot from 2017-07-10 07-02-04](https://user-images.githubusercontent.com/5289251/28002431-cb4decc8-653d-11e7-9203-49a56981af3e.png)
.

**Comment by hack0mate** [comment]
Ok, I'll try on my side. Anyway, thank you for your help.
