### ISSUE TITLE
cookie storage

### ISSUE THREAD

**Issue by vojtapolasek** [commixproject/commix#94]
Hi,
I try to run Commix against a web application. Between the web application and Commix sits Owasp Zaproxy, which provides authentication, e.g. it checks if Commix is still authenticated and if not, it tries to reauthenticate and set a new cookie. I don't know where is the problem, but when I try to do this with Commix, only the first request contains the cookie, then several following request don't then another request contains it, then again nothing... etc. When I try it with several other tools (Sqlmap and Xsser), it works nicely. How is the cookie storage solved in Commix?
Thanks alot.

**Comment by stasinopoulos** [comment]
Thanks for that issue report, i ll check it out soon.

**Comment by vojtapolasek** [comment]
Hi, Thank you for reply. Do you have any idea when are you going to look at this? I ask because I want to use Commix in larger project and this prevents me from doing that.
Thank you very much.

**Comment by stasinopoulos** [comment]
I am sorry but i cant confirm that issue in DVWA.

**Comment by stasinopoulos** [comment]
@vojtapolasek could you please confirm that this issue is still exists?
ps: Please update commix to the latest "dev" version and check again.
