### ISSUE TITLE
Runtime module

### ISSUE THREAD

**Issue by AnonymousRonin** [commixproject/commix#955]
Invalid runtime environment ('No module named '_sqlite3'').

Have tried all methods of download with no success.

**Comment by stasinopoulos** [comment]
This is some kind of an environment problem.

**Comment by AnonymousRonin** [comment]
Could you possibly more specific?

**Comment by stasinopoulos** [comment]
As i mentioned in my previous message, this is some kind of an environment problem in your system setup due to the fact that `sqlite3` is a standard Python module. For more, just Google the error message: `No module named '_sqlite3'`.
