### ISSUE TITLE
mixing | and || in the same payloads

### ISSUE THREAD

**Issue by Dawidradzi** [commixproject/commix#992]
## What's the problem (or question)?
some payloads this app using dont make sens in unix systems, example:
|[ 1 -ne $(echo BZAFIP |tr -d '\n' |wc -c) ] ||sleep 2
will never work
## Do you have an idea for a solution?
dont mix | and || in the same payload

## How can we reproduce the issue?

1. open terminal on your linux machine and type this payload:
username@localhost:~$ test|[ 1 -ne $(echo BZAFIP |tr -d '\n' |wc -c) ] ||sleep 5
i wont work
2. now remove unnecessary | from sleep like this:
username@localhost:~$ test|[ 1 -ne $(echo BZAFIP |tr -d '\n' |wc -c) ] |sleep 5
and will wait for 5 secound like intended
3. test any other combination on linux (i am using ubuntu) like:
uname|echo 1|echo 2
result is 2 so it execute all the commants
but
uname|echo 1||echo 2
result is 1 and that mean echo 2 was not executed

**Comment by stasinopoulos** [comment]
In any case that commix does not meet your needs, you can find a similar one that does.

**Comment by Dawidradzi** [comment]
you dont even check this probably, i just show you bug on you app
